#+title: Mutability

* Mutability
As mentioned in the [[file:./guessing.org][Storing Values with Variables]] section,by default,variables are immutable.
This is one of many nudges Rust gives you to write your code in a way that takes advantage of the =safety= and easy =concurrency= that Rust offers.
However,you still have the option to make your variables mutable.
Let's explore *how* and *why* Rust encourages you to favor =immutability= and why sometimes you might want to opt out.

When a variable is immutable, =once= a value is bound to a name, you can't change that value.
To illustrate this, generate a new project called variables in your project directory by using ~cargo new variables~

Then, in you new variables directory, open src/main.rs and replace its code with the following code, which won't compile just yet:
...

Save and run the program using ~cargo run~.
You should receive an error message regarding an immutability error, as shown in this output:
...

This example shows how the compiler helps you =find errors= in your programs.
Compiler errors can be frustrating, but really they only mean your program isn't safely doing what you want it to do yet;
they do not mean that you're not a good programmer!
Experienced Rustaceans still get compiler errors.

You received the error message ~cannot assign twice to immutable variable `x`~ because you tried to assign a second value to the immutable ~x~ variable.

It's important that we =get compile-time error= when we attempt to change a value that's designated as immutable because this very situation can lead to bugs.

If one part of our code operates on the assumption that a value will never change and another part of our code changes that value, it's possible that the first part of the code won't do what it was designed to do.

The cause of this kind of bug can be difficult to track down after the fact, especially when the second piece of code changes the value only sometimes.

The Rust compiler guarantees that when you state that a value won't change, it really won't change, so you don't have to keep track of it yourself.
Your code is thus easier to reason through.

But mutability can be very useful, and can make code more convenient to write.
Although variables are immutable by default, you can make them mutable by adding ~mut~ in front of the variable name as you did in [[file:./guessing.org][Chapter2]].
Adding ~mut~ also =conveys= intent to future readers of the code by indicating that other parts of the code will be changing this variable's value.

We're allowed to change the value bound to ~x~ from ~5~ to ~6~ when ~mut~ is used.
Ultimately, deciding whether to use mutability or not is up to you and depends on what you think is clearest in that particular situation.

* Constants
Like immutable variables, constants are values that are bound to a name and are not allowed to change, but there are a few differences between constants and variables.

First, you aren't allowed to use ~mut~ with constants.
Constants aren't just immutable by default -- they're always immutable.
You declare constants using the ~const~ keyword instead of the ~let~ keyword, and the type of the value must be annotated.

YOU MUST ALWAYS ANOTATE THE TYPE.

Constants can be delared in any scope, including the global scope, which makes them useful for values that many parts of the code need to know about.

Ths last difference is that constants may be set only to a constant expression, not the result of a value that could only be computed at runtime.

The compiler is able to evalute a limited set of operations at compile time, which lets us choose to write out this value in a way that's easier to understand and verify, rather than setting this constant to the value 10,800.

See the [[https://doc.rust-lang.org/reference/const_eval.html][Rust Reference's section on constant evalution]] for more information on what operations can be used when declaring constants.

Constants are valid for the entire time a program runs, within the scope in which they were declared.
This property makes constants useful for values in your application domain that multiple parts of the program might need to know about, such as the maximum number of points any palyer of a game is allowed to earn, or the speed of light.

Naming hardcoded values used throughout your program as constants is useful in conveying the meaning of that value to future maintainers of the code.
It also helps to have only one place in your code you would need to change if the hardcoded value needed to be updated in the future.

* Shadowing
As you saw in the guessing game tutorial in [[file:./guessing.org][Chapter 2]], you can declare a new variable with the same name as a previous variable.
Rustaceans say thata the first variable is shadowed by teh second, which measn that teh secodn variable is what the =compiler will see= when you use the name of the variable.
In effect, the second variable overshadows the first, taking any uses of the variable name to itself until either it itself is shadowed or the scope ends.
We can shadow a variable by using the same variable's name and repeating the use of the ~let~, keyword as follows:

Filename: src/main.rs
...

This program first binds ~x~ to a value of ~5~.
Then it creates a new variable ~x~ by repeating ~let x =~, taking the original value and adding ~1~ so the value of ~6~.
Then, within an inner scoep created with the curly brackets, the third ~let~ statement also shadows ~x~ and creates a new variable, multiplying the previous value by ~2~ to give ~x~ a value of ~12~.
When that scope is over, the inner shadowing ends and ~x~ returns to being ~6~.
When we run this program, it will output the following:
...

Shadowing is different from marking a variable as ~mut~ because we'll get a compile-time error if we accidentally try to reassign to this variable without using the ~let~ keyword.
By using ~let~, we can perform a few transformations on a value but *have the variable be immutable* after those transformations have neen completed.

The other difference between ~mut~ and shadowing is that because we're effectively creating a new variable when we use the ~let~ keywrod again, we can change the type of the value but *reuse the same name*.

For example, say our program asks a user to show how many spaces they want between some text by inputting space characters, and then we want to store that input as a number:
#+begin_src rust
let spaces = "    ";
let spaces = spaces.len();
#+end_src

The first ~spaces~ variable is a string type and the second ~spaces~ variable is a number type.
Shadowing thus spares us from having to come up with different names, such as ~spaces_str~ and ~spaces_num~; instead, we can reuse the simpler ~spaces~ name.
However, if we try to use ~mut~ for this, as shown here, we'll get a compile-time error:
#+begin_src rust
let mut spaces = "   ";
spaces = spaces.len();
#+end_src

The error says we're not allowed to mutate a variable's type:
...

Now that we've explored how variables work, let's look at more data types they can have.
