:PROPERTIES:
:ID:       0663959f-ff8f-4ea3-bcea-d652de4e1c28
:END:
#+title: Elm

* Elm languages
** no runtime exceptions
elm uses type inference to detect corner cases and give friendly hints.

NoRedInk switched to Elm about four years ago, and 300k+ lines later, they still have not had to scramble to fix a confusing runtime exception in production.

** fearless refactoring
The compiler guides you safely through you changes, ensuring confidence even through the most widereaching refactorings in unfamiliar codebases.

** Understand anyone's codebases
All Elm programs are written in the same pattern, eliminating doubt and lengthy discussions when deciding how to build new projects and making it easy to navigate old or foreign codebases.

** Fast and friendly feedback
Famously helpful error messages.
Even on codebases with hundreds of thousands lines of code, compilation is done in a blink.

** Performance
Elm has its own virtual DOM implementation, designed for simplicity and speed.

All values are ~immutable~ in Elm, and the benchmarks show that this helps us generate particulary fast Javascript code.

** Javascript interop
Elm can ~take over a single node~, so you can try it out on a small part of an existing project.
