:PROPERTIES:
:ID:       55178df1-94bb-4920-9a11-897b3cf6e609
:END:
#+title: ColdReading

* Woman do not approach to say.
 they engineer opportunity for you to approach.
 But like us, they're victim of their own projection
 They believe because their signs are obvious to other women that obvious to us.
 Ladies do you here this?
 Let me give you a little bit perspective ladies.
 You can have beautiful women. walk up to a guy to this.
 And he'll go,
 When i'm gonna she meant by that?
 We're just not that smart!
 you're operating on a completely different set of social cues, you guys want the same thing you just different languages to talk about it.
 you just use different languages to talk about it
 the most subtle signs for a man are some of the most blatant and sometimes threatening for women.
 because the signals they're sending you are out here we don't perceive anything until it's right here
 so when we go to approach a woman and by the way most of your socialization ladies has designed all the good ones to keep from approaching you.
 In case you didn't know that. oh yes
 most people's socialization has programmed you guys and girls to send out signals that will keep the good ones from approaching you and only the sociopath narcissists and pickup artists will make the leap.
 What sense does it have to do with neural physiology then?
 that we're sending you signals and we respond to them that human beings respond have a certain  grammar why would we shut down opposition?
 It's not neurotizability it's social programming
 hollywood
 One of the problems again this is going way off in a squirrel chasing mod but one of the problems that we have is that we have been programmed hey first of all to play hard to get.
 you guys are all taught this right. play hard to get have value show scarcity the problem is is that the social cues your design the body language that you've been taught to use to stimulate or signal hard to get actually says don't approach.
 And so what happens is the guys who are waiting who are looking for invitations that you're approachable. won't the ones who will respect your boundaries and actually be upstanding guys who are will want to help and be the good mates you're looking for they won't approach you without a tremendous amount of encouragement.
 because the cues you're sending out tell them not to.
 So who will?
 people with no ability to read social cues narcissists people who don't care about your boundaries.
 Okay now i know there's exceptions to every rule.
 the problem we have is if you want us if ladies if you want to signal hard to get in a way that makes people want to chase you be seen in the company of a lot of people vy;ing for your time.
 be seen as being having your time in demand as opposed to being off in a corner.
 because ironically, the body language of shyness can often be misinterpreted as the body language for aloofness to somebody who's extremely attractive.
 when people are shy or in a timid place they tend to make themselves small
 alpha people dominant people take up vertical horizontal space they take up vertical space this is the body language of charisma.
 in speed attraction 2.0 i showed you the heart the open heart trust trigger right where you literally can go from being just the average dude.
 To radiating energy like that right it's and this was desinged by women this is the way it works is you imagine there's a plexiglas screen over your heart, and you just want to show people your heart when you talk to them.
 As opposed to this.
 Feel the difference?
 All i'm doing is imagining there's a screen here and i'm beaming my heart energy toward them.
 I'm letting them see my heart.
 Changes my posture and changes the level of credibility that i radiate to an audience.
 When you are shy and this is true for guys as well when you start going through being timid or unafraid and afraid what happens is you ten to make yourself smaller
 You close in on yourself
 You create boundaries
 Now when people see this, you may be just waiting for somebody to come and talk to you because you don't want to make the first move but that's not how you're interpreted.
 It's not how you're interpreting. especially if you're attractive.
 If you're putting this out and nobody's approaching you, the first thing they do is they don't have a story.
 You haven't told them why you're doing what you're doing so they create a story
 They create a story about why you don't want to be approached. she must be a snob.
 She's obviously attractive so she should have got she must be a bitch.
 Sorry that's what happens right?
 I don't make the rules i just exploit them i mean report them
 However, if you want to invert that equation a change your body language problem that we have and somebody asked about approaching so i'll just answer this question.
 The problem both genders have with approaching is different.
 Women don't have a problem with you approaching as a rule, they have a problem with getting you to leave.
 Because we're not that smart.
 You can be the same the one guy in a group of women and at some instant moment every woman knows the conversation is over and they disappear.
 And all of a sudden the guy's like..
 ah i'm alone. right. we didn't catch it
 why because when your neurology was evolving, you were communicating with each other you were cooperating you were developing relationships and interpreting what behaviors mean in your world.
 We're out killing mastodons. we look at it. do we eat it. do we take it home and mate with it or run away from it.
 That's how we think right
 We developed a different set of scanning mechanisms.
 Women's neurology evolved because they had to survive.
 They had to learn how to manage you idiots.
 Keep you around, keep you interested, and they had to learn to rely on each other.
 They had to learn very quickly in that unit who they could rely on who they couldn't and they had to do it based on the meanings they could extrapolate from your behaviors.
 So if we look at this from a hypnotic language perspective men work in cause and effect
 We see it => we hit it
 We see it => we chase it
 We see it, it sees us => we run from it
 right? cause and effect
 Women work mostly and both side do it but there's a predominance, 'equivalence'.
 We left the toilet seat up because we forgot
 We missed jack's soccer game because traffic was a bitch.
 there was two of the traffic jam the boss kept us late there was a tough client that's why i was late.
 And your wife looks at you and says "if you loved your sone you'd have been there"
 Why because being at the soccer game means you love your son.
 this is where 80% of our problems in communication with our gender partners lie.
 ladies we're not as complex as you are.
 When we leave the toilet seat up, it's because we're freaking idiots and we forgot.
 It's not that we have no respect for the feminine gender in the home you've built together.
 You see guys? guys like huh?
 It's a language thing, but remember ladies your brains are actually more developed than ours.
 Your copis colosseum the bridge between your right hemisphere and your left hemisphere is almost twice our size.
 You see size matters. right?
 Man only process language on one side of their brain.
 Women use both
 We're half wits. i love guys i'm an equal opportunity hater so you know.
 But it's easier for you as women, to understand us sometimes than it is for us to understand you gentlemen
 If all you got out of today was remember that every behavior that you generate, means something to them.
 Think about that before you do anything.
 Just stop for a moment and ask yourself how is she going to interpret that?
 And then think again.
 I have a whole workshops that i do back in san diego where it's just about romance and attraction and relationships and for me it's co-ed audiences and mostly women believe it or not.
 And it's to me it's high comedy when i explain what the behaviors and the activities of the opposite gender are being interpreted by them. it's like terror on each other's faces.
 But this is the problem. most women go to female dating coaches to bitch about men
 Most guys go to male dating coaches to complain about women
 Get in the same room and understand each other.
 Seek first to understand
 You both want the same thing just in a different order. you really do
 You use slightly different words to describe it and there's a slightly different syntax but it the same thing.
 here's something ladies you didn't know.
 We're more sensitive than you are.
 did you know that?
 You see from the chinese medical perspective men are young on the outside we're strong and mentally tough like bull.
 And we're cotton candy on the inside.
 We can't handle vulnerability like you can.
 It hurts us worse.
 We don't bounce back as fast.
 So for a man to give you the intimacy and the vulnerability you're looking for that's a big deal.
 That's what you're looking for.
 Men fall in love faster did you know that?
 Women fall out love faster did you know that?
 You get over us real quick.
 This is why you guys have the ladies that's why you have the babies.
 You can take it we can't.
 So intestinally internally you're stronger than we are. so factor that in.
 that in um that's about have we covered this kind of stuff pretty well another thing i want you to pay attention to is when you're in close to somebody this is going to go into face reading.
 When you're paying attention to their eyes, prolonged eye contact generates attraction okay not creepy iconic.
 That's not waht i'm talking about.
 When we talk about eye contact we're talking about positive eye contact.
 So pot ism
 Well, i jsut want to go back to that example of a woman sitting like this.. blabla...
 First of all, remember that whether you're male of female, confident people take up space.
 So expand yourself horizontally that doesn't mean you stand like this that's a guy thing.
 but if you do cross your legs, don't cross your legs real in tight does that make sense?
 So good posture. I like to call it the maryland switch.
 the open heart trust trigger is a really good.. way to sit imagine there's a plexiglas screen here.
 and you're just beaming and letting people see your heart.
 if that if you just imagine that your body language your body would your posture would take over the rest.
 THe next part is, make positive eye contact.
 Positive eye contact, again is not the serial killer stare.
 And it's and there's always a smile with it but the difference is there has to be a wrinkles at the zygomatic.
 When we get to the face reading part you'll actually see the long-term effects of this.
 This the eyes have to crinkle. you see the crilkling? right?
 if you see someone who's dead from the nose down? Not good.
 This is like the donal the divine what's the trump's wife's name Melania
 that's the melania trump simle.
 That's nto what we're doing.
 Positive eye contact has to be good shen in the eyes which means a twinkel or wide open eyes not you know scared eyes, but nice oepn eyes, smile, with the wrinkles up by the sides of the head.
 That signals positive eye contact.
 When you enter a venue and this could be male of female.
 And i practice this all the time.
 I'm walking throught the convention.
 As you walk through a venue, meet people's eyes and look at who gives you positive eye contact.
 POSITIVE EYE CONTACT.
 That means you make eye contact with someone and you see this, not this
 Those are the people who are open to being approached if you're doing walk up or street hypnosis.
 That's one of the first things you look for. positive eye contact
 Next thing you do give them an eyebrow flash.
 huh! he closed a loop holy sheet!
 Positive eye contact, eyebrow flash, smile.
 combine that with a good posture and an openheart trust trigger you get a lot more people coming up to you.
 If you want to be signaled as having being hight value in somebody's world be seen in the company of a lot of men.
 or other people fighting for your attention.
 Wanting for your attention that signals status and guys that's what ladies look at.
 if there's a big crowd around you, there must be a reason.
 providers not having 100 bills or something.
 This called social proof.
 It's an affinity tactic.
 We look at the responses of the people around us to determine what's appropriate.
 does it make sense?
 anything else on this?
 this one a little bit from different direction than i planned but yeah.
 Why did you say to be seen in the company of men?
 Well, what i actually said was the company of the men or women all vying for your attention.
 We want whenever we remember in college there was always the popular crowd, they always had everybody wanting their attention wanting their validation things like that.
 Learn how to be those people?
 If you want to play the hard-to-get game.
 If you want to play the scarcity game.
 If you don't have a trot, if you're not part of a tribe build your own.
 Build your own. that's what i teach my students go build your tribe.
 Let me show you how to do it build your tribe.
 But that's going to help you be more unfluential and charismatic.
 You're going to generate an affinity tactic more people are going to flock to you because they see other people flocking to you.
