* Starcitizen Star engine
64 bit

** Open world
seamless transition from space to ground ~without loading~

fully explorable planets

surface generation on client & server

streaming -> expansive exteriors with interiors

real time transit, biome generation

enviornment procedural generation

*

* 영어 잘하는 법 첫번째,
** 영어의 필요성을 이해하는 것입니다
왜냐구요?

사람은 필요하지 않으면 하지 않는 동물이거든요.

만약 지금 영어가 하기 싫은 기분이라면,

영어가 필요한 이유를 몸소 느끼지 못한겁니다

그렇기에 각자 자신만의 이유를 찾는게 중요하고,

제가 영어를 배우는 이유를 설명해드릴테니,

여러분은 자신만의 이유를 생각하면서 들어보세요.

*** 영어 잘하면 좋은점

**** 영어권에서 돈을 벌수 있다
우리나라 인구는 5천만명이죠.
지금에야 한국이 세계적으로 유명해지고 있지만 (BTS, 블핑, 뉴진스)
우리나라가 알려지기 시작한 건 얼마되지 않았다는거, 알고계시죠?
외국인들이 한국어를 배웠다고 해도, 그 수가 적을거라는 것은
어느정도 예상할 수 있습니다. (감으로요)

근데 영어권 인구는 native,
그니까 모국어가 영어인 사람들이
무려 3억 4천명입니다 (2023.12.17 현재)
그리고 영어는 국제적으로 통용되는 언어가 된지도 오래됐잖아요?
영국이 식민지 지배를 할 때부터니까 어림잡아 200년을 될겁니다.
이렇게 되니 어떻게 되요?

native가 아닌 영어 사용자들은 이제
13억명 이에요

그니까 26 대한민국 이라는 겁니다. (한국 x 26)

이게 진짜 엄청 중요한거에요

아직 와닿지 않으시는 분들을 위해 예를 들자면,

만약 우리가 장사를 한다고 합시다.

우리나라에서 물건을 팔면, 최대 5천만명에게 팔 수 있죠?

이것만 해도 감이 좀 오시죠?

영어 native 국가에서 팔면 어떻게 될까요?

그렇죠, 잠재고객이 순식간에 3억 4천명으로 늘어납니다. (한명 => 여러명, 자막으로 3억 4천)

아까도 말했지만,
영어권 사람들을 모두합치면, 13명이라니까 ㅋㅋㅋ
뭐 말 다했죠.

**** 한국과의 정보 격차로 인해 이익을 본다

영어를 배우시면 자연스럽게 외국의 소식을 "먼저" 보실 수 있습니다.

이건 외국에 계시거나, 영어를 잘하시는 분들이라면,

분명히 느끼고 계실거에요 (보고계신가요?)

제 예시를 들자면,

저는 chat gpt를 주변 지인들 보다

3,4개월 먼저 알고있었습니다. (미리써봤음)

제가 개발자라서 그런 것도 있겠지만,

꼭 그런 것도 아닌게, 제 주변에 다른 개발자들도 모르는 분들이 많았거든요.

그리고 애초에,

이 채널도 제가 번역한 영상을 위주로 올리고 있잖아요?

이게 전부 "영어"로 인한 이점인겁니다.

개인적으로 없어저야할 격차라고 생각하지만,

그러려면, 모든 국민이 영어를 잘하게 되어야 할 겁니다. (파이팅)

**** 한국과 다른 영어권 문화를 즐길 수 있다
영어권은 한국에 비해 좀 더 자유로운 문화를 가졌다는 것
다들 알고 계실겁니다.

그런데, 이런 점이

이게 정말 어떤 의미인지, 느껴보는 것이 중요합니다.

한마디로 "자유의 기준"이 다릅니다.

한국에서는 "이래야만 한다"는 게,

외국에서는 "굳이?"가 되는거에요

이렇게 자유의 기준이 낮으면 어떻게 되느냐,

"다양성"이 높아집니다

사람들이 엄청 다양해지는 거에요

물론, 다양성이라는 건 동전처럼 양면이 있습니다.

창의성 있는 사람들이 자주 나오지만,

그만큼 이상한 사람들도 자주나오죠 ㅋㅋ

이런 점에서 영어를 사용하시면, 정말 다양한 인간군상을 보실수가 있습니다.

우리나라와 다른 문화를 경험한다는 게,

바로 이런 것 아닐까요


* 여기까지,
영어를 잘하는데 꼭 필요한,

자신만의 이유 만들기에 대한 영상이였습니다.

혹시, 공감하시는 부분이 있는지,

아니면, 다른 생각을 가지고 계신지 궁금하네요.

* 저는 1년 전만해도,
번역기 없이, 거의 기초적인 단어조차 읽을 수 없을 만큼 정말 초보자였습니다.

하지만 지금은 왠만한 영어글을 번역기 없이 읽을 수 있고,

원어민이 하는말을 바로바로 대충이나마 이해할 정도의 실력이 됐습니다.

영어를 배우면서, 이걸 학창시절에 알았으면,, 라는 생각을

진짜 정말 많이 했어요

영어를 배우는 방법에 대해서는 시중에 자료들이 넘쳐납니다.

어떻게 배워라 ~, 뭐가 어떻게 좋다 ~

여러분들이 더 잘 아실거에요.

하지만 저는 방법보다 이유가 더 중요하다고 생각해요

이유가 있으면, 배우는 시간이 고통스럽지도 않고 오히려 재밌다구요 ㅋㅋ

우리나라의 교육방식에 대해서도 할말이 많지만,

너무 늘어지는 것 같아서 여기까지 하겠습니다 ( 궁금하신가요? )

여러분 이유가 없는데, 방법을 찾지마세요

그렇게 되면 정작 방법을 찾아도, 실행하지 않을 겁니다 (제가 그랬어요)

그럼 모두들,

영어를 배워야하는 자신만의 이유를 찾았으면 좋겠습니다

끗
