#+title: Logarithm

* What is the Logarithm?
The exponent that a base could become some number.

* Logarithmic
How many times do you break the stick if the stick is being 1 unit?

The inverse function to [[file:./exponential.org][exponentation]].
That means that the logarithm of a number =x= to the base =b=
=is= the exponent to which ~b~ must =be= =raised= to =produce= x.

For example, since ~1000 = 10^3~,
the logarithm base 10 of 1000 =is= 3, or log10(1000) =is= 3.

3 is a logarithm based on 10 of 1000
This mean, when you have 1000, and you have to divide by 10, you should have to break 3 times to get 1

The logarithm of ~x~ to base ~b~ =is= =denoted= as logb(x),
or without parentheses, logbx,
or even without the explicit base, logx,
when no confusion =is= possible,
or when the base does not matter such as in [[file:./big-o.org][big O notation]]

* Omitting
** Common Logarithm
If the base of any numbers is a `10`, you can ommit the base 10.

This is called common logarithm.

** Natural Logarithm
If the base of any numbers is a `e` (Euler's number), you can ommit the base e.

*** Why use Euler's number?
1. Natural growth and decay
   'e' appears naturally in descriptions of continuous growth or decay,
   such as compound interest, radioactive decay, or population growth.

2. Calculus
   ?? is its own derivative,

3. Complex analysis

4. Probability theory

5. Engineering and physics

6. Computer science

7. Natural logarithms
   In(x), based on 'e', often simplifies calculations compared to logarithms with other bases.
  
* 역사
커다란 숫자를 계산하기 편하도록 만든 개념

a를 x번 곱하면 b가 된다

x = log a b

a를 몇번 곱해야 b가 될까?

** log n 은 n 보다 작은가? (항상)

*** log n < n

-1만 사용해, 4로만드는데 필요한 곱셈 횟수 = 불가능
-2만 사용해, 4로만드는데 필요한 곱셈 횟수 = 2 < 4
-3만 사용해, 4로만드는데 필요한 곱셈 횟수 = 1.~ < 4
-4만 사용해, 4로만드는데 필요한 곱셈 횟수 = 0.0000...1 = 0 = 불가능
-5만 사용해, 4로만드는데 필요한 곱셈 횟수 = 불가능
0만 사용해, 4로만드는데 필요한 곱셈 횟수 = 불가능
1만 사용해, 4로만드는데 필요한 곱셈 횟수 = 불가능

( log를 다룰때는, 밑수가 2이상인 경우를 가정한다 )

2만 사용해, 4로만드는데 필요한 곱셈 횟수 = 2 < 4
2만 사용해, 5로만드는데 필요한 곱셈 횟수 = 2.~ < 5
2만 사용해, 6로만드는데 필요한 곱셈 횟수 = 2.~ < 6
( log n 는 소수점 단위로 커짐, n 은 1단위로 커짐 )
( log n 의 증가량 < n 의 증가량 )

2만 사용해, 4로만드는데 필요한 곱셈 횟수 = 2 < 4
3만 사용해, 4로만드는데 필요한 곱셈 횟수 = 1.~ < 4
4만 사용해, 4로만드는데 필요한 곱셈 횟수 = 1 < 4
( 모든 밑수에 상관없이, 등식을 만족 )

*** 결론
log의 밑수가 2이상임을 가정했을때,

모든 log n 은 n 보다 작다.

log n < n 이 성립한다.

*** 의미
재료로 사용할 값이 2이상 일때,
( 스마트폰의 길이가 2이상 일때 )

재료를 곱해, 목표로 하는 값을 만들때 필요한 횟수는
( 스마트폰의 길이을 곱해, 노트북의 길이를 만들때 필요한 횟수는 )

목표로 하는 값보다 항상 작다.
( 노트북의 길이보다 항상 작다 )

사과 1개

그게 3개 더, (3개)

그게 3개 더, (9개)

그게 3개 더, (27개)
