:PROPERTIES:
:ID:       c65686ee-2e8d-468d-8a59-283816bfb687
:END:
#+title: SelfPr
* Skoler는 덴마크어로 "학교" 라는 뜻 입니다.

사람인 이상, 태어난 이후부터 죽기전까지, 배움을 멈추지 말아야 한다고 생각합니다.
그러나 저는 항상 학습에 대한 어려움이 많았습니다.
평범한 가정에서 태어나, 다른 아이들과 마찬가지로 학창시절을 보냈습니다.
하지만 그 와중에 같은 선택을 내리지는 않았습니다.
지금 제 주변의 대부분의 지인들은 평범한 인문계 고등학교를 졸업했지만,
저는 특성화 고등학교를 선택했습니다.
당시에 해킹에 관심이 있었던 저는 어떻게든 관련이 있는 과목을 가르치는 학교에 가고 싶었고, 그런 이유에서 내린 선택이였습니다.
반면에, 그 당시 저는 본능적으로 현재 교육에 대한 반발심을 느끼고 있었습니다.
마치 누군가가 "이 길은 네 길이 아니야." 라고 말하는 것 같았습니다.
저는 그 본능을 따랐고, 그게 옳다고 생각했기에, 남들이 뭐라하든 제가 생각한대로 행동했습니다.
하지만 대부분의 학생들이 그렇듯, 저는 혼란의 연속이였습니다.
특성화 고등학교에서의 생활은 저의 기대와는 달랐습니다.
제가 관심있던 내용에 관한내용은 거의 없다시피하고, 왜 배워야 하는지 모르겠는 과목들만 즐비했습니다.
그리고 불안했던 저는, 스스로의 판단을 멈추고 그저 남들이 해야한다고 말하는 것들을 추구했습니다.
어떻게든 수도권의 좋은 대학에 입학하기만 하면 된다는 말을 믿었습니다.
학교에서의 상대적인 성적이 우수했던 저는, 특정 전형으로 입학해 사람들에게 나름 좋다고 알려진 학교에 입학했습니다.
하지만 이게 끝일리가 없죠.
대학에서도 "배움"이라는 주제는 끊임없이 저를 괴롭혔습니다.
고등학교에서 대학으로 옮겨가면서, 저의 상대적인 성적은 낮아질 수 밖에 없었고,
학교는 저를 "학사경고자", "학습부진학생"이라고 불렀습니다.
맞습니다. 저는 학창시절 내내 학습에 어려움을 겪고 있었습니다.
하지만 시간이 아무리 지나도, 저는 "왜 공부를 해야하는지" 그에 대한 해답은 찾지 못했습니다.
주변에서 말하는 이유들에 대해서 납득이 가지않았기 때문이죠.
무엇보다도, 제게 필요한 것이 아니라고 느껴졌기에 흥미가 없었고,
흥미가 없었기에, 남들의 계속된 권유는 강요로 느껴졌습니다.
그래서 저는 "나도 재밌으면서, 남들에게도 도움이 되는 일을 하자" 라고 생각하고,
실제로 활용되는 기술이 좋았던 저는, 눈에 보이는 웹사이트 만들기를 배우기 시작했습니다.
