#+title: Dropshipping

* Bring people to my website

* Branding
** What is nike?
** What does it stand for?
** What does it mean?
** What is the emotion behind the product?
** How do you feel when you purchase a product from nike?
** Why are they able to charge high prices?

* 7 Figure Blueprint
1. Locate a wnning product
2. Order the product off of amazon and ship it to your HOME
3. Remake Trending videos
4. Start Posting 2-3 organic tiktok's daily
5. Organic videos that perform well turn thenm into spark tiktok ads
6. continue creating and posting videos
7. You should easily be hitting $10k revenue per day
8. Begin outsourcing your customer support through a virtual assistant
9. Connect with a 3pl team and start using them for fulfillment
10. Invest in a UGC agency and also work with influencers
11. Hire a marketing agency to take over google ads, tiktok, ads, facebook ads, etc
12. Hire an email & sms retargeting team
13. Focus on buying in bulk
14. You have a real brand, with custom products, fast shippiing and a huge team of people helping you succeed

* Potential Income

** TikTok ADS
$10-$20k / Day

** Google ADS
$10-$20k / Day

** EMAIL & SMS
$5k /DAY

** Influencer
$10k / Day

** TikTok ORG
$1-%5k / Day

* Quotes
#+begin_quote
What would you attempt, if you knew you could never fail? - Robert H.Schuller

Human's don't create abundance, they craet lack - Arnold Patent
#+end_quote

* 7 Principle
** of Mentalism
#+begin_quote
The all is mind; the universe is mental

#+end_quote

** of Polarity
#+begin_quote
Everything is dual; everything has poles; everything has its pair of opposites; like and unlike are the same; opposites are identical in nature, but different in degree; extremes meet; all truths are but half-truths; all paradoxes may be reconciled
#+end_quote

** of Rhythm
#+begin_quote
Everything flows, out and in; everything has its tides; all things rise and fall; the pendulum-swing manifests in everything; the measure of the swing to the right is the measure of the swing to the left; rhythm compensates.
#+end_quote

** of Cause and Effect
#+begin_quote
Every cause has its effect; every effect has its cause; everything happens according to law; change is but a name for law not recognized; there are many planes of causation, but nothing escapes the law.
#+end_quote

** of Gender
#+begin_quote
Gender is in everything; everything has its masculine and feminine properties; gender manifests on all planes
#+end_quote

* Precise goals
$10K profit a month
$50K revenue a month
20% profit margin
$12,500 revenue a week
$1,780 revenue a day
$40 x 45 = $1,800 a day
