* intro
자 오늘은 Doom Emacs를 설치해볼겁니다.

Doom Emacs 가 뭐냐?

그전에 Emacs 부터 설명을 하자면,

다양한 형식의 문서를 편집할 수 있는 문서 작성 프로그램

예를 들자면, 일정 관리나, 프로그래밍에 주로 사용합니다

제가 일정 관리를 하면서,

그동안 많은 앱들을 써왔는데,

기본적으로 약간 불편한 점들이 있어서


이것 저것 갈아타다 보니까

여기까지 오게 됐다. => Emacs

Emacs의 장점이 무엇이냐?

강력한 단축키 + 커스터 마이징 기능

누구에게 도움이 되냐?

컴퓨터를 많이 쓰는 사람
- 사무직 - 한글X
- 프리랜서
- 사장님
- 학생 - 논문
- 프로그래머 - 소스코드 작성

일정 관리를 해야하는데, 컴퓨터로 하고 싶은 사람
- 노트 앱들 => 노션, 옵시디언, 에버노트... 이런 것들을 사용해 왔는데,
- 원하는 기능만 있으면 되는데, 궂이 궂이 들어간 추가 기능들 때문에,
  내가 원하는 기능을 찾기가 번거로운 거지
  이걸 또 내맘대로 바꾸기에는 => 프로그램 사용 방법을 배워야 함
  => 내가 원하는 바로 그 상태로 만들수있다는 보장 도 없고, 일단 그렇게 하는 사람이 없음 => 결국 내가 직접 찾고, 맨땅에 헤딩하면서 설정해야되는데 이게 시간이 오래걸림

- 불편함
  + 내가 원하는 기능이 없다.
  + 안예쁘다.
  + 관리가 번거롭다
    - 보통 노트를 작성한다는 것은 => 정리하기 위함이거든 => 정리가 깔끔해야됨

    - 일기, 하루 일정, 피드백 => 매번 늘어나고 => 중구난방이 되버림 => 나중에 찾기가 어려워 => 아무리 검색기능이 있어도

    - 새로운 파일을 만들고, 정리하고, 찾고 이런 모든 과정들, 메모에 필요한 모든 과정들을 좀 더 간소화하고 싶다 => nvim

      nvim 도 나중에 기회가 되면을 설명할 텐데,
      하여튼 종착지는 emacs에요.


메모앱 커스터마이징
=> 원하는 기능만 쏙쏙 골라내서 나한테 최적화된 메모앱을 사용하고 싶으니까.

=> 예쁘기까지 하다?


* 프로그래머에게 유용하다.
프로그래밍을 할 수 있다. => 사실상 지금은 프로그래머가 가장 많이 쓰지만,
컴퓨터를 많이 사용하는 사람이고, 평소에 메모를 많이 하는 사람이라면,
메모관리를 정말 쉽게 할 수 있고, 여러 메모를 자유롭게 움직여 다닐 수 있다

** 여기 까지가 Emacs 에 대한 설명


* Doom emacs가 뭔지

emacs를 더 쉽게 관리할 수 있도록 만들어진, 관리 프로그램이라고 보면된다.

emacs에 관련된 여러가지 설정들을 파일에 쓰면, 내가 원하는 데로 앱을 커스터마이징 할 수 있다.

이게 emacs만가지고 서도 할 수 있기는 한데, 기존의 앱들과는 다르게, emacs는 거의 모든 부분을 커스터마이징

내가 원하는 기능을 가진 플러그인을 설치하고, 이를 설정해야되는데,

플러그인 마다 설정해야 될 부분도 많고

입문자 입장에서 어떤 플러그인이 자주사용되는지도 모른다


그래서, 사람들이 자주사용하는 플러그인이랑, 패키지 설치관리자 를 합쳐서,

emacs를 커스터마이징하기 편하게 만든 프로그램이 바로 doom emacs다~

그래서 이제, 설치를 해볼 건데요.

설치를 진행하기 전에,

대부분 설치는 터미널에서 진행될건데요,

따라하기만 하면되니까 잘 따라오시길 바랍니다.



* 순서도
영상하단에 있는 사이트를 들어와서, 명령어를 복사해줍니다.







제 환경은 mac 이기 때문에,

mac 기준으로 설치를 진행할겁니다.









우선 brew 를 설치해줍니다.

개발자가 사용하는 앱스토어 같은거라고 생각하시면 되요.









지금부터 나오는 링크들은

영상 하단에 있으니까, 참고해서 설치하면 됩니다.
