#+title: Agent

* Agent
In this chapter, we will learn how to =keep= and =share= state between multiple entities.
If you have previous programming experience, you may think of globally shared variables, but the model we will learn here is quite different.
The next chapters will generalize the concepts introduced here.

If you have skipped the Gettig Started guide or read it long ago,
be sure to re-read the [[file:../start-guild/processes.org][Processes]] chapter.
We will use it as a starting point.

** The trouble with state
Elixir is an immutable language where nothing is shared by default.
If we want to share information, which can be read and modified from multiple places, we have two main options in Elixir:

- Using Processes and message passing
- [[https://www.erlang.org/doc/man/ets.html][ETS (Erlang Term Storage)]]

We covered processes in the Getting Started guide.
ETS is a new topic that we will explore in later chapters.
When it comes to precesses though, we rarely hand-roll our own, instead we use the abstractions available in Elixir and OTP:

- [[https://hexdocs.pm/elixir/Agent.html][Agent]] - Simple wrappers around state.
- [[https://hexdocs.pm/elixir/GenServer.html][GenServer]] - "Generic servers" (processes) that encapsulate state, provide sync and async calls, support code reloading, and more.
- [[https://hexdocs.pm/elixir/Task.html][Task]] - Asynchronous units of computation that allow spawning a process and potentially retrieving its result at a later time.

We will explore most of these abstractions in this guide.
Keep in mind that they are all implemented on top of precesses using the basic features provided by the VM, like ~send~, ~receive~, ~spawn~ and ~link~.

Here we will use Agents, and create a module named ~KV.Bucket~, responsible for storing our key-value entries in a way that allows them to be =read= and =modified= by other processes.

** Agents
[[https://hexdocs.pm/elixir/Agent.html][Agents]] are simple wrappers around state.
If all you want from a process is to keep state, agents are a great fit.
Let's start an ~iex~ session inside the project with:
#+begin_src bash
iex -S mix
#+end_src

And play a bit with agents:
#+begin_src elixir
{:ok, agent} = Agent.start_link fn -> [] end
#=> {:ok, #PID<0.135.0>}
Agent.update(agent, fn list -> ["eggs" | list] end)
#=> :ok
Agent.get(agent, fn list -> list end)
#=> ["eggs"]
Agent.stop(agent)
#=> :ok
#+end_src

We started an agent with an initial state of an empty list.
We updated the agent's state, adding our new item to the head of the list.
The second argument of [[https://hexdocs.pm/elixir/Agent.html#update/3][Agent.update/3]] is a function that takes the agents' current state as input and returns its desired new state.
Finally, we retrieved the whole list.
The second argument of [[https://hexdocs.pm/elixir/Agent.html#get/3][Agent.get/3]] is a function that takes the state as input and returns the value that ~Agent.get/3~ itself will return.
Once we are done with the agent, we can call [[https://hexdocs.pm/elixir/Agent.html#stop/3][Agent.stop/3]] to terminate the agent process.

The ~Agent.update/3~ function accepts as a second argument any function that =recieves= one argument and =returns= a value:
#+begin_src elixir
{:ok, agent} = Agent.start_link fn -> [] end
#=> {:ok, #PID<0.135.0>}
Agent.update(agent, fn _list -> 123 end)
#=> :ok
Agent.update(agent, fn content -> %{a: content} end)
#=> :ok
Agent.update(agent, fn content -> [12 | [content]] end)
#=> :ok
Agent.update(agent, fn list -> [:nop | list] end)
#=> :ok
Agent.get(agent, fn content -> content end)
#=> [:nop, 12, [%{a: 123}]]
#+end_src
As you can see, we can modify the agent state in any way we want.
Therefore, we most likely don't want to access the Agent API throughout *many different places* in our code.
Instead, we want to =encapsulate= all Agent-related functionality in a single module, which we will call ~KV.Bucket~.
Before we implement it, let's write some tests which will outline the API exposed by our module.

Create a file at ~test/kv/bucket_test.exs~ (remember the ~.exs~ extension) with the following:
#+begin_src elixir
defmodule KV.BucketTest do
  use ExUnit.Case, async: true

  test "stores values by key" do
    {:ok, bucket} = KV.Bucket.start_link([])
    assert KV.Bucket.get(bucket, "milk") == nil

    KV.Bucket.put(bucket, "milk", 3)
    assert KV.BUcket.get(bucket, "milk") == 3
  end
end
#+end_src

~use ExUnit.Case~ is responsible for setting up our module for testing and imports many test-related functionaliy, such as the ~test/2~ macro.

Our frist test starts a new ~KV.Bucket~ by calling the ~start_link/1~ and passing an empty list of options.
Then we perform some ~get/2~ and ~put/3~ operations on it, asserting the result.

Also note the ~async: true~ option passed to ~ExUnit.Case~.
This options makes the test case run in parallel with other ~:async~ test cases by using multiple core in our machine.
This is extremely useful to speed up our test suite.
However, ~:async~ must only be set if the test case does not rely on or change any global values.
For example, if the test requires =writing= to the filesystem or access a database, =keep= it synchronous (omit the ~:async~ option) to =avoid= race conditions between tests.

Async or not, our new test should obviously fail, as none of the functionality is implemented in the module being tested:
#+begin_src elixir
#** (UndefinedFunctionError) function KV.Bucket.start_link/1 is undefined (module KV.Bucket is not availablep)
#+end_src

In order to fix the failing test, lets' create a file at ~lib/kv/bucket.ex~ with the contents below.
Feel free to give a try at implementing the ~KV.Bucket~ module yourself using agents before peeking at the implementation below.

The first step in our implementation is to call ~use Agent~.
Most of the functionality we will learn in this guide, such as ~GenServer~ and ~Supervisor~, follow this pattern.
For all of them, calling ~use~ generates a ~child_spec~ function with default configuration, which will be handy when we start supervising processes in chapter 4.

Then we define a ~start_link/1~ function, which will effectively start the agent.
It is a convention to define a ~start_link/1~ function that always accepts a list of options.
We don't plan on using any options right now, but we might later on.
We then proceed to call ~Agent.start_link/1~, which receives an anonymous function that returns the Agent's initial state.

We are keeping a map inside the agent to store our keys and values.
Getting and putting values on the map is done with the Agent API and the capture operator ~&~, introduced in the Getting Started guide.
The agent passes its state to the anonymous function via the ~&1~ argument when ~Agent.get/2~ and ~Agent.update/2~ are called.

Now that the ~KV.Bucket~ module has been defined, our test should pass! You can try it yourself by running: ~mix test~.

** Test setup with ExUnit callbacks
Before moving on and adding more features to ~KV.Bucket~, let's talk about ExUnit callbacks.
As you may expect, all ~KV.Bucket~ tests will require a bucket agent to be up and running.
Luckily, ExUnit supports callbacks that allow us to skip such repetitive tasks.

Let's rewrite the test case to use callbacks:
#+begin_src elixir
def module KV.BuckTest do
  use ExUnit.Case, async: true

  setup do
    {:ok, bucket} = KV.Bucket.start_link([])
    %{bucket: bucket}
  end

  test "stores values by key", %{bucket: bucket} do
    assert KV.Bucket.get(bucket, "milk") == nil

    KV.Bucket.put(bucket, "milk", 3)
    assert KV.Bucket.get(bucket, "milk") == 3
  end
end
#+end_src

We have first defined a setup callback with the help of the ~setup/1~ macro.
The ~setup/1~ macro defines a callback that is run before every test, in the same process as the test itself.

Note thata we need a mechanism to pass the ~bucket~ pid from the callback to the test. We do so by using the *test context*.
When we return ~%{bucket: bucket}~ from the callback, ExUnit will =merge= this map into the test context.
Since the test context is a map itself, we can pattern match the bucket out of it, providing access to the bucket inside the test:
#+begin_src elixir
test "stores values by key", %{bucket: bucket} do
  # `bucket` is now the bucket from the setup block
end
#+end_src

You can read more about ExUnit cases in the [[https://hexdocs.pm/ex_unit/ExUnit.Case.html][ExUnit.Case module documentation]] and more about callbacks in [[https://hexdocs.pm/ex_unit/ExUnit.Callbacks.html][ExUnit.Callbacks docs]].

** Other agent actions
Besides getting a value and updating the agent state, agents allow us to get a value and update the agent state in one function call via ~Agent.get_and_update/2~.
Let's implement a ~KV.Bucket.delete/2~ function that deletes a key from the bucket, returning its current value:
#+begin_src elixir
@doc """
Deletes `key` from `bucket`.

Returns the current value of `key`, if `key` exists.
"""
def delete(bucket, key) do
  Agent.get_and_update(bucket, &Map.pop(&1, key))
end
#+end_src

Now it is your turn to write a test for the functionality above! Also, be sure to explore [[https://hexdocs.pm/elixir/Agent.html][the documentation for the Agent module]] to learn more about them.

** Client/Server in agents
Before we move on to the next chapter, let's discuss the client/server dichotomy in agents.
Let's expand the ~delete/2~ function we have just implemented:
#+begin_src elixir
def delete(bucket, key) do
  Agent.get_and_update(bucket, fn dict ->
    Map.pop(dict, key)
  end)
end
#+end_src

Everything that is inside the function we passed to the agent =happens= in the agent process.
In this case, since the agent process =is= the one receiving and responding to our messages, we say the agent process =is= the server.
Everything outside the function =is= happening in the client.

This distinction is important.
If there are expensive action to be done, you must consider if it will be better to =perform= these actions on the client or on the server. For example:
#+begin_src elixir
def delete(bucket, key) do
  Process.sleep(1000) # puts client to sleep
  Agent.get_and_update(bucket, fn dict ->
    Process.sleep(1000) # puts server to sleep
    Map.pop(dict, key)
  end)
end
#+end_src

When a long action =is= =performed= on the server, all other requests to that particular server will =wait= until the action =is= =done=, which may =cause= some clients to timeout.

In the next chapter, we will explore GenServers, where the segregation between clients and servers is made more apparent.
