#+title: Index


* Sentances
** By Name
*** John Wanamaker
I have enough trouble overcoming my own limitations without fretting over the fact that God has not seen fit to distribute evenly the gift of intelligence.

People don't criticize themselves for anything, no matter how wrong it may be

*** Sigmund Fruid
Everything you and I do springs from two motives:
- sex urge
- the desire to be great

*** Dewey
desire to be important

*** Lincoln
Everybody likes a compliment

*** William James
the craving to be appreciated

craving > longing > desire > wish

*** A father's hogs
The hogs didn't care about the ribbons they had won. But Father did.

The prizes gave him a feeling of importance.

*** Andrew Carnegie
Here lies one who knew how to get around him men who were cleverer than himself
*** Dale Carnegie
Personally I am very fond of strawberries and cream, but fish perfers worms.
So when I went fishing, I didn't think about what I wanted.

I think about what they wanted.

I didn't bait the hook with strawberries and cream.
Rather, I dangled a worm or a grasshopper in front of the fish and said,

#+begin_quote
"Wouldn't you like to have it?"
#+end_quote

I interested in what I want. ETERNALLY
They interested in what they want. ETERNALLY
*** Henry Ford
#+begin_quote
If there is any one secret of success, it lies in the ability to get the other person's point of view and see things from that person's angle as well as from your own.
#+end_quote

** By Title
*** Only way to move person
There is only one way under high heaven to get anybody to do anything
That is by making the other person /wants/ to do it.

THERE IS NO OTHER WAY.

The only way I can get you to do anything is by giving what you /want/.

So, what do you /want/?

*** Trap
I was extremely glad I had not criticized her ~as she has requested~.
*** One thing that certain
You act because you wanted something.

* Laws
** Criticism
criticism -> resentment -> demoralize -> still not correct the situation that has been condemned

*** 실천
**** 상대방의 단점 찾기
**** 단점이라고 생각하는 이유가 진리인지 파악하기
**** 그 단점을 절대 내 입 밖으로 내지말고, 좋은 방향으로 이용하기 (장점화)

** the desire to be important
desires(wants) -> act

#+begin_quote
Every act you have ever performed since the day you were born was performed because you wanted to something.
#+end_quote

*** What do people wants? (List of good subject for questions)
**** Health & The preservation of life
**** Food
**** Sleep
**** Money & The things money will buy
**** Life in the hereafter
**** Sexual gratification
**** The well-being of our children
**** A feeling of importance

*** Results of this desire
because of this,

- Dickens write his immortal novels
- Sir Christopher Wren design his symphonies in stone
- Rockefeller amass millions that he never spent
- The richest family in your town build a house _far too large for its requirements
- You wear the latest styles, drive the latest cars, and talk about your brilliant children
- Many boys and girls into joining gangs and engaging in criminal activities

*** How you get your feeling of importance?
- John D.Rockefeller got his feeling of importance by giving money to erect a modern hospital to care for millions of poor people whom he had never seen and never would see.

- Dillinger got his feeling of importance by being a bandit, a bank robber and killer.
*** 실천
**** 상대방 행동 관찰하기
**** 그 행동 인해, 상대방이 얻고자하는 것이 무엇인지 찾기
**** 상대방이 원하는 것을 미끼로, 좋은 방향으로 이끌기
** How to move person
*** 실천
**** 상대방을 설득하고 싶을때
Who cares what i want than what they want?

***** 내 입을 다물기

***** 스스로에게 질문하기
내가 상대방이라면, 이것을 좋아하는 이유는 무엇인가?

어떻게 하면, 상대방이 이걸 좋아하게 할 수 있을까?

***** 그들이 원하는 것에 대해 말하기
이 행동이, 그들이 원하는 것을 얻는데 어떻게 도움을 주는지 설명하기

- 과정: 어떤 단계를 거쳐, 그것을 얻게 되는지
**** 연습하기
설득하는 글 수집 -> 수정하기

***** 설득하는 글
구매유도
~해달라
요청

**** 주의사항
무조건 상대방이 원하는 것을 먼저말하기

* What I have to do
** to satisfy the desire to be important
Improve my people's self-asteem
** 상대방을 움직이게 만들기
심지어 목적에 관해서는 단 한마디도 필요없다.
