#+title: Alex

* About Alex
그저 취미로 헬스하던 사람이
아무것도 없는 상태로 시작해서

현재 []개의 사업체를 운영할 수 있게 해준
지금 [1000억원]의 돈을 벌게 해준
지금 [1000억원]의 자산가가 되게 해준
지금 []명의 구독자를 모으게 해준

* 조절 할 수 있는 것 vs 조절 할 수 없는 것

- 직접적으로 컨트롤 할 수 있는 것
  최대한 많이 하기 (more Volume!)

- 간접적으로 컨트롤 할 수 있는 것
  피드백의 지표

| Things that you can control | Things that you can't control |
|-----------------------------+-------------------------------|
| Input                       | Output                        |
| Think & Action              | Emotion                       |

* Rule
** 가난한 사람 전부에게 팔 능력을 갖출때까지, 부자들에게만 팔기
고객이 원하는 가치가, 돈의 비중이 낮은 상품

*** 가격 정하는법 (프리미엄 전략, 손해론)
100만원을 쓸 마음이 있는 사람에게, 10만원에 팔기 -> 90만원 손해

10만원 쓸 마음이 있는 사람에게, 100만원짜리 거절당하기 -> 10만원 손해

*** 유튜버 광장 추가내용
광고 단가가 높은 시청자 층

~테크~, ~부동산~, 투자, 주식, ~창업~

** 제발 알리기. 아무도 내 행동을 모르고, 내가 존재한다는 것을 모른다.
너무나 많은 광고에 내가 질려도, 날 모르는 사람이 너무 많다

날 알아야, 나에게 돈을 줄 수 있다

- 조회수 높은 글을 참고하여, 나만의 게시글로 바꿔보기

** 1달에 1억3천 미만의 매출이라면, 마케팅에 집중하기
피드백을 받을 수 있는 사람이 충분해야한다 (너무 적으면 안된다)

나쁜 피드백이 너무 많으면, 입소문이 커져 마케팅이 역효과가 난다 (마케팅 멈추고, 퀄리티 올리기)

** 1년에 13억 미만의 조회수라면, 1채널 1아바타 1상품만 사용하기
모든사람한테 Yes == 비즈니스에 No

집중할 수 없다면, 좋아질 수 없다

많은 채널 == 많은 시간과 비용

** 항상 무료로 시작하기
무료 상품은 피드백을 얻기 위함이다
- 신뢰가 없으면, 10원도 안쓴다.

지인 추천하는 사람들이 있다 (무료 광고)

유료 상품으로 전환하는 사람들이 있다 (잠재 고객 유치)

** 증거 만들기 (무료로 시작해야하는 이유)
내 말 100번 보다, 증거 1개가 더 신뢰성 있다

- 약속하지 말고, 증거 보여주기
  (댓글반응, 리뷰, 사진, 동영상, 논문, 뉴스..)

- 가능한 최신 증거 만들기
  (너무 오래돼서 지금은 잘 모르겠는데?)

** 가격을 올리기
너무 많은 고객으로 인해, 인력이 부족할때

고객 수를 35% 줄이고
나머지 고객 (65%)에게 2배를 받으면
결과적으로 이득이다 (인력이 부족하다는 사실로 설득)

물가 상승률을 고려해, 해마다 가격을 조정해야만 한다

지금의 퀄리티를 유지하려면, 가격을 올려야만 한다는 것을 설득

이득과 손해를 계산하여, 이득이 더 높은 비율을 유지하도록 하기

** 고객과 대화하기
모든 문제의 답은 고객에게 있다

모르겠다 -> 물어보기

*** 왜 구매했는지?
더 원하는 것이 있으신가요?

*** 왜 구매하지 않았는지?
그것을 바로잡기 위해 제가 해야할 일은 무엇인가요?
** C.L.O.S.E.R (세일즈)
Clearfy - 왜 나에게 왔는지, 고객의 입으로 질문하기
Labeling - 고객이 원하는 것을 정의내리기
Overview - 지금까지 어떤 결핍을 겪어왔는지 질문하기
Sell the Vacation - 고객이 누리게될 경험을 설명하기 (고객이 성공할 수 밖에 없는 3가지 핵심 요소)
Explain - 구매하지 않는 이유 설명하기
Reinforce - 고객이 좋은 선택을 했다고 느끼게 해주기 (24간내로 약속, 빠를 수록 좋다)
** 새로운 것을 시작하기 전에, 기존의 것을 10배 더하기
지루하다고 안하고 있는 그게, 내 수익을 10배 늘려줄 작업이다.

문제를 파악할 수 없는 상황이라면, 너무 멀리왔다. 속도를 줄여야 한다

** 스트레스 받는다고, 행동 바꾸지 말기
#+begin_quote
스트레스는 절대 사라지지 않는다.

성장할때든, 실
#+end_quote


지금 문제라고 생각하는 것은, 나중에도 남아있을 것이지만
그땐 내가 문제라고 생각하지 않을 것이다
(상황이 바뀌는게 아니라, 내가 바뀐다)

** 고객은 마지막 구매를 기준으로 상품을 평가한다
구매주기를 늘릴수록, 고객이 많이 남아 있다.

고객은 자신의 돈이 빠져나갈때, 그 서비스를 판단한다.

그들의 돈이 빠져나가기 전에, 서비스의 질을 올려라

*** 결제시기 맞춰, 이벤트 진행
고객 만족도 상승, 재구매 유도

고객들의 결제시기를 몰아놓아야,
고객 이벤트시기를 결정하기 편하다.

*** 구독요금제 기간늘리기

1달 단위 -> 3달 단위 -> 반년단위 -> 1년단위

**** 연간 구독자 할인 이벤트 + 무조건 짧은 기간보다 훨씬 저렴하게 설정
1달에 한번 만족시키는 것보다, 1년에 한번 만족시키는게 더 쉽다
한번에 많이 받으면, 더 빠르게 성장가능

** 톱밥 팔아보기
내가 버리고 있는 것을, 누군가 이미 팔고있을 수 있다

이것을 활용하기만하면, 모든게 수익으로 바뀐다

** 세일즈 무장하기
세일즈는 현금흐름의 핵심

*** 고객의 특정 우려사항과, 그에 대한 해결책이 정리된 엑셀파일을 제공
영업 담당자의 "고객 거절 대응 장비" 창고 채우기
- 직원 교육을 효과적으로 할 수 있다

** 세일즈와 광고는 결합하기
한명, 한부서가 담당하기 (CRO - Chief Revenue Officer)

세일즈와 광고가 분리된 회사는, 자신의 책임을 타인에게 떠넘기기 쉽다

광고가 세일즈의 구멍을 메우고, 세일즈가 광고의 구멍을 메운다

광고: 1-many
세일즈: 1 1

고객에게 충분한 정보를 제공하면, 그들은 구매 결정을 할 수 있다

이미 충분한 정보를 가지고 있는 사람들은, 별다른 노력을 하지 않아도 산다.
충분한 정보를 가지고 있지 않은 사람들은, 정보를 제공해주길 바란다.

Maybe to Yes

아마도를 그래요로

** 3명의 리더
*** 고객을 데려오는 일을 담당하는 리더
*** 약속된 것을 전달하는 일을 담당하는 리더
*** 매일 매일 실행하는 일을 담당하는 리더
*** 시간 흐름
**** 처음
나 혼자 3가지 일을 담당

**** 나중
나는 3가지 리더중에 어떤 리더상인가?

** 높은 기준을 가진 사람에게 맞기기
모든 일의 상급자는, 높은 기준과 낮은 오차율을 가져야한다.

내가 높은 기준을 가질 수 없다면, 그런 사람을 데려와라

지금 여기 있는 사람중에, 가장 높은 기준을 가진 사람은 누구인가?
(그 사람이, 담당자가 될 자격을 갖춘자)

*** 경력, 실력보다 중요한 "기준"
높은 기준을 가진 사람을 대체할 수 있는 사람은 없다.

시간이 흐르면 결국 기준이 높은 사람이 승리한다.

** 알맞는 사람 데려오기

*** 후보 물색하기
그들이 나에게 배우는 것 보다, 더 많이 가르쳐주고 있나?

자신이 하는일을 정확히 알고 있는 사람과, 그렇지 못한 사람 구분하기

그들이 하는 말의 양과, 질에 집중

그들이 어떻게 성공에 영향을 주었는지

"당신이 지원한 분야에서 성공하려면 어떻게 해야한다고 생각하나요?"

당신이 할 일은 무엇인가

당신은 당신이 지원한 분야의 일을 성공하기위해 어떤 행동을 할 것인가

어떤 행동이, 어떤 과정을 통해, 어떤 결과를 도출하는지 알고 있는사람

*** 선택하기
팀의 기준을 높여줄 수 있는 사람

그 사람이 들어옴으로써, 우리 팀의 기준이 높아지는가?
(Yes - 우리가 성장한다, 회사가 성장한다)

당신의 최고는 아직 오지 않았다.

최고의 파트너는 미래에 있다. (과거가 아니라)

#+begin_quote
신입은 어떻게 해야할까?
- 높은 기준은, 경력과 학력을 따지지 않는다.
#+end_quote
** 다른사람이 내가 원하는대로 움직이지 않는 5가지 이유
메신저를 공격하지말고, 메세지를 공격하라

*** 내가 원하는게 뭔지 몰랐다
소통 문제

- 내가 원하는 것을 명확하게 밝혔나?
- 서면으로 하지않아, 그들이 까먹지 않았나?

*** 그 일을 어떻게 하는지 몰랐다
훈련이 필요한 경우

*** 그 일을 언제해야 하는지 몰랐다
*** 그 일이 하기 싫었다
동기의 부재

**** 어떻게 그들의 동기를 이끌어낼 것인가?
금전적 인센티브, 응원

하지만, 자유와 재투자 만큼 좋은 인센티브는 없다

***** 자유 & 재투자
그들에게 자발성을 부여하고,

그 자발성에 투자하라.

***** 금전적 보상의 한계
금전적 보상으로, 자발적인 노력을 얻을 수 없다.

***** 상대방을 발전시키기 위해 투자하기
#+begin_quote
그들에 투자했는데, 떠나면 어떡하나요?

그들에게 투자하지않았는데, 계속 남아있으면 어떡하나요?
#+end_quote

*** 무언가 장애물이 있다
**** 엄청나게 근사한 백만달러짜리 사무실을 이용하지 않는 편집자들
그들이 집에서 작업하는 이유

~업로드 속도가 느려서~
** 가장 어려운 일은, 내가 모르는 일이다
가장 쉬운일은, 내가 아는 일이다

우선순위

*** 원래 하던것만 하려고 하는 것
레벨 2를 깼으면, 3으로 넘어가라.

계속 2만 깨려하지말고.

**** 계속 2만 깨는 이유
이전에 못했던 것을, 이젠 할 수 있게 되었다는 기쁨을 또 다시 느끼고 싶어서

*** 우리는 항상 모를 것이다.
이미 가지고 있는 것만이, 아는 것이다.

성장하고자 한다면, 반드시 모르는 분야에 뛰어들어야 한다.

*** 실패는 필연적이다.
내가 모르는 분야에 뛰어들고 있다면.

내가 성공만 하고 있다면, 내가 아는 분야라는 뜻이고
내가 아는 분야라는 것은, 더 이상 성장할게 남지 않았다는 뜻이다.

**** 해야하는 것
내가 멈추지만 않는다면, 결국 성공하는 일

하나의 우선순위를 정하고, 그것을 성공할 때까지 멈추지 않는 것.
** 많이 해결하는 것이 중요한게 아니다
*** 각각의 일이 얼마나 성장하게 해주는 지가 중요하다
*** 나무를 가지치기 하는 이유
**** 큰 그림을 봤을때, 곁가지를 쳐주면 더 잘자라니까

** What?
*** 미팅 늘리기
*** 우선순위 낮은일 제거하기
*** 소통 강화하기
*** 진행상황을 눈에 명확하게 띄도록하는 환경만들기
*** 인센티브 만들기

* Mind
** Action alleviates anxiety

#+begin_quote
You're nervous because you're underprepared.

Hard to be nervous when you've actually done the same thing the same way 100 times in a row.
#+end_quote

** Spend all your resources to get more learning faster
I'm the asset investing in

*** Value of things
Money < Skill

** Do not try to be a intelligent
Try not to be a stupid

** First Questions
*** Why can't we 10x this thing
> The reason of this questions are our main problems.
> these problems are the thing we need to solve
> and if we solved, we will get the 10x

** The balance is the myth

** You're not a patient
You just have lack of skills and how to behave in certain condition.

Anyone is going to care about is how you act how you behave how you do based on series of conditions.
You just need to expose yourself to the conditions so that you can get the repetition so that you can learn how to overcome it.

** Is it condusive to your goals?
How do we increase the likely that you do act the way that you want to?

*** Logic
What is that mean?

*** Evidence
How do you know that?

How many time it happened?

What did that result in?

*** Utilities
And so what? Who cares? Why does this matter?

What do we do about it?

** Hardship is a opportunity

** Figuring out
You cannot say you can't figure something out before try for 20 hours

** Frame
Ask the girl
Shoot the shot
Launch the business
Run the ad
Quit the job
Take the risk

When you're 85 years old
and on your deadbed,
You're not gonna wish you had fewer crazy story
* View
** 사업가의 시각 연습하기
*** 내 주변에 있는 사업아이템
- 침구류 생산 판매
- 충전기 생산 판매
- 벽지 생산 판매
- 창틀, 창문 생산 판매
- 가구 생산 판매
- 음료 생산 판매
- 스마트폰 생산 판매
- 의류 생산 판매
- 내가 방금 먹음 음식, 생산 판매

*** 너무 짜다
* Millionaire
** Level 1
*** Who you are
***** knowlwdge
#+begin_quote
A millionaire means that you have over $1M in investable assets minus your house

14억 (집 제외)
#+end_quote

***** skills
#+begin_quote
A trait is a bundle of skills

기술을 모으면, 특징이 된다


The more you learn, the better you get
The better you get, the more $$$ you get

더 많이 배우면, 더 나아지고
더 나아지면, 더 많이 얻는다


Knowledge tells you where to put effort to learn the most money-making skills

지식은 내 노력을 어떤 기술에 투자해야
가장 많은 돈을 벌 수 있는지 알려준다
#+end_quote

****** Sales
- active listening
- repeating words
- body language
- vocal tonality
- rhetorical skills

******* Marketing
- media
- headline
- webpage
- conversion

******** Acquisition

***** motivation
#+begin_quote
If you're motivated to become a millionaire it's because you lack a million dollars

만약 내가 10억부자가 될 동기부여가 돼있다면,
그건 내가 10억이 없기 때문이다.
#+end_quote

***** environment
#+begin_quote
How do I make it as easy as possible to work as hard as I can?

날 최선을 다하도록 만드려면, 어떻게 해야할까?


The season of 'NO'

방해요소를 거절하기
#+end_quote
*** Who to sell to
#+begin_quote
Help the person that you can provide the most value to.

내가 가장 많은 가치를 제공할 수 있는 사람을 돕기
#+end_quote
**** Calculating
1,400,000,000

***** Difficulty
인원수가 적을수록 난이도가 낮다

****** 14,000,000원 * 100명
기간 나누기

******* 4년
1년에 3,500,000원 25명
1달에 300,000원 3명


****** 1,400,00원 * 10000명
**** Helping fewer people
Becuae you don't have money,
and you don't have resources either.

Start with most expensive version of the product.

***** Tesla
1. 로드스터 - 최고가 모델을 맨처음 발매
2. 모델 S - 고가 모델
3. 모델 X - 중저가 모델
**** People to sell to
***** Someone with ~PAIN~ who is like you
나와 같은 고통을 겪고 있는 사람

#+begin_quote
You help someone who is like you overcome something that you overcame in the past.

내가 과거에 극복했던 것을, 극복하도록 도와주기
( 해결책을 알고 있는 - 고통, 문제 )
#+end_quote

***** Someone you share a ~PASSION~ with
나와 같은 열정을 공유하는 사람

***** Someone who needs ~PROFESSIONAL SKILLS~ you have
내가 가진 전문기술이 필요한 사람
**** PAIN, PASSION, PROFESSION
***** PROBLEM
- Who don't have enough information about that ~PAIN~.
- Who don't have enough information about that ~PASSION~.
- Who don't have enough information about that ~PAIN~.

****** I want them to have the urgency to solve it now
#+begin_quote
It has to be something that they want to solve right now, because this will overcome all of the people who are like "ah I'm gonna think about it". They keep pushing it off.

사람들은 항상 다음으로 미루기 때문에, 지금 바로 시작해야하는 이유를 내세워야 한다.
#+end_quote

***** MONEY
Who have the money to spend

****** I want them to have the authority to spend it
**** Disclaimer
#+begin_quote
Make sure you're going to be in a market that's at least flat or growing.

최소한 정체되어있거나, 성장하는 시장에 뛰어들어라
줄어들고 있는 시장은 완전히 배제하라
#+end_quote

*** What to sell
*** UNIQUE
#+begin_quote
I don't want anyone else to be able to sell it.
#+end_quote

*** EXPENSIVE
#+begin_quote
To make more money per unit.
#+end_quote

*** STICKY
#+begin_quote
Things that people don't just buy once but keep buying again and again.
#+end_quote

*** AIR
#+begin_quote
Something that doesn't cost me alot to deliver
#+end_quote

*** SCALE
#+begin_quote
The matter is the incremental cost of adding a customer.

중요한건, 1명의 고객을 끌어오는데 필요한 비용이다.
#+end_quote

| Easy to scale         | Hard to scale |
|-----------------------+---------------|
| Add a use to software |               |
** Level 2
*** Get them to buy
100M Leads: How to Get Strangers To Want To Buy Your Stuff

**** Find Out
***** Core 4
****** Warm Outreach (EASIEST)
Telling people 1:1 who know you about your stuff

******* Easiest Offers
Hey I'll help you for free

1. 3~5시간 정도를 써서, 다른 사람의 문제를 해결하는 것을 도와준다

2. 앞으로 나와 함께 유료로 일해보는게 어떤지 제안한다

****** Cold
Telling people 1:1 who don't know about your stuff

******* Social

****** Content
Telling many people who know you about your stuff

******* SNS

****** Paid Ads
Telling many people who don't know about your stuff

******* SNS

***** 4 Lead getters
****** Customers
People who have bought your stuff who can refer other to your business.

****** Employees
Team members who can do the core 4 for you

****** Affiliates
Businesses with similar customers that can send them to you

****** Agencies
Specialized services you can hire to help you do the core 4

**** Get Them To Buy
***** Clarify
#+begin_quote
We need to clarify why they're even took the time to reach out.

Why did you respond to our ad.

Why did you respone to my email.

Why did you comment on my post?

If they responded in some way then they've taken the first step.

~Clarify the PROBLEM~
#+end_quote
***** Label
#+begin_quote
It sounds like, you are here(current), you want to get here(desire), and this is the thing(fix the gap, remove the obstacle) that's getting in the way

We have sword that can fix the gap, remove the obstacle and kill the monster.

And ultimately get them to their desire to state.

But we can't sell, unless we have a gap
#+end_quote
***** Overview
Overview the past pain

****** Pain Cycle
#+begin_quote
What did you done before?
How that workout for you?

pieces that they liked you compare you associated your solutions

pieces that they don't like you associate why you didn't work, why your solutions different this time.
#+end_quote

반복할수록, 가지지 못한 현실에 대한 좌절감이 정확히 드러난다
***** Sell the vacation
They care about themselves, their problems.
They don't care about your product.

****** three-pillar pitch

***** Explain their concerns
****** They blame their circumstances for why they can't do something
I don't have ~TIME~.
I don't have ~MONEY~.
This isn't right for me (fit question)

****** They blame other people for why they can't do something
Someone else has to make the decision
I didn't like a similar product

****** They avoid the decision altogether which is basically blaming themselves
I'm not ready

***** Reinforce the decision
On Boarding

24~48 hour post purchase

****** Make as many promises as you can

In that time period and keep them
#+begin_quote
Hey, this is going to happen in the next 30 minutes.
this is going to happen.
You're going to get an email. and then click that link.
this is going to happening.
#+end_quote

****** BAMFAM
Book A Meeting From A Meeting

- no one ever gets left in the cracks
- no one falls through

The reason that a lot of customers cancel, is because you said someone's going to reach out them and they thought it was going to take 30 minutes you didn't set the expectations takes two days and "You know what? This isn't for me. I changed my mind"

#+begin_quote
You should take =NOTES=.
You never want a customer to repeat themselves.
Share that note to your employees and make them to care.

And then customer satisfaction will improve and they buy more stuff in the future.

You will get more customers if you review the note before call to them!
#+end_quote
*** How many times they buy
#+begin_quote
The businesses that make customers worth the most, make the most money.

Any business can benefit from making customers worth more.
#+end_quote

**** Increase the price (EASIEST)
***** 5-5-5 model
#+begin_quote
Every 5 items you sell, bump your price by 20%
#+end_quote

You can do this FOREVER until people stop buying.

Gross Profit x Conversion Rate = $$$

#+begin_quote
Never discount to get a sale
#+end_quote

**** Buy more times
Buying over a period of time.

**** Quantity
Increasing the quantity all at once.

**** Quality
Ways to make service higher quality

- Better Team
- More Support
- Priority Support
- Extended Hours

**** Decrease costs
**** Buy something new or different
pairs or complimentary to whatever you core offer is.

#+begin_quote
Sometimes complementary items bring in more profit than the core item.
#+end_quote
**** Decrease the quantity
Decrease the number someone buys

#+begin_quote
Instead of buying 160 pieces, you just buy 20.
You can have a down cell.

The reason that this make make you more money is that it actually makes you more money per person you talk to. Not per customer.

This is you make money here when you take a no and turn into a yes.
And taking a small no turning into a small yes, and then later you ahve all these other things to turn into a big yes.
#+end_quote

**** Lower quality
The discount version
The economy class version

#+begin_quote
You have Junior reps who answer.
You have extended times.
You don't get calls.
You only get chat support.
#+end_quote
*** Who helps you
#+begin_quote
The most valuable skillset as a business owner is getting other people to do work for you.
#+end_quote

**** Somebody doesn't do what I want them todo, why that be?

***** They didn't know that you wanted them to do it at all.
Because you hadn't told them or you weren't clear about

***** They didn't have any motivation to do it.
#+begin_quote
Explain how what they do contributes to the company's success

If every person in the organization knows how they tie what they do directly or indirectly to you being successful as a business, then they have a larger motivation for why they should do it.
#+end_quote
***** They didn't know how to do it.
****** Document
What you do to get the result
****** Demonstrate
You do in front of them using document.

Follow the check list and look at what happens
****** Duplicate
Finally you know HOW

***** They didn't know when you wanted them to do it by.
***** Something blocking them from doing it.

**** Business
***** Acquisition
Marketing & Sales

Letting people know about your business, and getting them to exchange money for a service/product

***** Delivery
Creation and Delivery of the product and/or service to the customer

***** Operations
Everything that _supports the other 2 pillars_ and allows them to scale.

IT, Legal, Finance, Payroll, HR
**** Getting a partner or cofounder
***** Problems
#+begin_quote
Most Partnerships come from two guys or two girls who are buddies and say hey let's get like, "we have fun hanging out!" "let's talk about business together"

The problem is, let's say they both love marketing and sales, or they both love product, or they both love operational stuff just like people and things like that.

*Over indexed*
#+end_quote
***** They have to have,
- A skill you lack
- Time you lack
- Capital you lack
** Level 3
*** Keep your advantage - Leverage
How much output you get relative to your input. (최소 투자 최대 효용)

#+begin_quote
It's not mean good or bad. it's just *how much you get*.

Understanding what work is can give you more leverage.

Work = Volume * Leverage = Output

It's not about how hard you work. It's how much you get for the work you do.

In the beginning you need to do lots of volume to build skill (leverage)

The more you do -> the better you get
The better you get -> the more you like it
The more you like it -> the more you do

When you have low leverage (skill), you need to compensate with high volume.

Work hard in order to work smart
#+end_quote

***** Brand
Click the rate (CTR)
Conversion rate (CONV)

Once people do that -> they are able to say yes or they willing to say yes at *higher price*.

주력 상품과 비교되는 상품 같이 보여주기

***** People
#+begin_quote
You can combine multiple people's life experience to my business
#+end_quote

***** Work Once -> Use it millions of times
****** Writing
Book
Blog

***** Skill
*** Stick with it
#+begin_quote
Compound interest is the eighth wonder of the world.

The first rule of compounding: Never interrupt it unnecessarily.
#+end_quote

**** Focus
Focus = Quality x Quantity -> No

If you say no hypothetically to literally everything except for one thing, you would define that person as incredibly focused probably obsessive.

**** Process
#+begin_quote
It is easier to grow a business from $10M-$15M than it is from $0-$5M
#+end_quote
***** Uninformed optimism
New opportunity looks great because you don't know anything about it.

***** Informed Pessimism
New opportunity looks bad because you know the downsides.

***** Valley of despair
Peak pesimism in a new opportunity where most people give up

#+begin_quote
What happens most times is they never get to step forward.
#+end_quote

***** Informed optimism
Now you informed about it.

***** Achieve
*** Get better & Keep getting better
**** The ability to learn
***** Courses and Experts
***** Double down volume
You can acquire skills by common factors analysis.

****** Common factor analysis
You can find the better ways to do.

If no one know about how to get what I want, there is no other way to get it.

- What are my top 10% of customers?
- What do they have in common in terms of what they did and who they are?
- What are the bottom 10%?
- What did tehy do and who are they?

******* Top one
What did the top 10% have that other one didn't have?


******* Bottom one
What did the bottom 10% have that other one didn't have?

****** Overcome shying
One of the things that people shy away from in the beginning is how low leverage you are.

You have no Capital
You have no friends
You have no other people who can help you out

So it's just you and when you start, you suck.

#+begin_quote
The pain of how hard it is forces you to get better.
#+end_quote

| Twick    | More!!      |
|----------+-------------|
| headings | open rates  |
| offer    | response    |
| ad hooks | click rates |
|          |             |

***** What you loved
Are you willing to give that up in order to keep your goal?

The reason that I have such an intimate relationship with my goals is because my goals have fed me more than anything in my life.

They have helped me become the person that I want to be, because they ahve orientedm behavior to help me do the activities that create the character traits that create the coutcomes.

#+begin_quote
If you want to be exceptional, you have to be willing to be the exception.

If you change the variables, you change the outcome.
#+end_quote
** Final
#+begin_quote
You are the outcome not your million dollars.

I don't want to stop getting better until the day I die.
#+end_quote
* First $10,000 online
Passion -> Profit

** Free Traning Project
*** STAGE1 - Reach out to friends
_Why Homies?_

#+begin_quote
It wasn't really that hard because people knew that I love Fitness

And I just said, I'll help you for free
#+end_quote

Problem:
#+begin_quote
Sure, Maybe you can say that you can do that.

But why should I believe you?
#+end_quote

You need to get PROOFs (before anything)

**** Before & Afters
**** Testimonials
테스트 대상 선택

사람들은 나의 제안에, 자신의 상황을 대입할 것이다.

그들의 상황에 딱맞는 제안을 하면, 성공확률이 높아진다.

많은 사람들이 겪는 문제를 해결 -> "나도 되겠다!"
얘도 된다! -> "나도 되겠다!"

**** RESULTS
*** STAGE2 - Referrals
_Why Referrals?_

**** Referrals are FREE
**** Make likely to buy at HIGH PRICES
HIGHER conversion rate & HIGHER price!
**** More likely to referral
#+begin_quote
After provide the value, and ask them

"I need like a few more, can you sent me some friends that have seen your results"

Homies of homies referrals
- They just knew that I'd helped their friend.
#+end_quote
*** STAGE3 - The FREE traning project (Community)
#+begin_quote
"Hey when you refer someone, just donate $500 to $1000 to the charity of your choice, that way you stil have skin in the game but it's still effectively free in that you're not paying me."

당신이 이 것을 추천한다면 $500 ~ $1000 달러를 기부하세요.
#+end_quote

공공의 이익을 위해 일을 진행하고, 기부자들을 모으기.
- 난 어떤사람들을 위해 일하고 있나
- 왜 그들을 도와야 하는가
- 내가 돈을 받지 않는다는 것이 확실한가?
  돈을 받는다면 비중은 얼마나 되는가?
  자신의 돈이 어디에 쓰이는 지, 정확하고 정기적인 보고 시스템

_그들의 전후 결과를 증명할 수 있는 증거를 남기기_

*** STAGE4 - Skinny to Swole (Officialy launching)
#+begin_quote
I asked new people to pay $200 a month for 12 weeks to go from skinny to swole.

I had all these great transformation pictures from my friends
#+end_quote

자선 프로젝트를 통해 끌어모은 사람들에게, 유료 상품 제안하기
- 그들이 친구의 결과를 보고 들어왔다면, 유료 상품 제안을 이상하게 생각하지 않을것이다?

** What I did RIGHT
*** Walk the walk
"the BIG obvious"

내가 돈이 없다면, 돈 버는 방법 강의를 팔지 못한다. (사람들이 못 믿는다)

"You should be the biggest walking billboard of whatever it is you sell"

#+begin_quote
If i got results for myself, and gotthen results for other people, that people would believe that I could get results for them. at least some level.
#+end_quote

PROOF > PROMISE
*** Lived cheap
#+begin_quote
I knew that I could live on 50 grand for at least 2 or three years if I had to.
#+end_quote

**** Living cheap 101
- Grocery shop at Costco
- Meal prep ALL food
- Don't eat out
- Don't go out

**** Working more
- Makes you money from working
- Saves you money because you're spending time working

*** Start FREE
**** Proof's are very efficient
That will actually make me more money jsut over a longer period of time

You can change these to more money in later

- Testimonials
- Feedback
- Referrals
**** Price Law
Always FULL PRICE or FREE

한번 가격을 내리면, 모든 사람들에게 이렇게 말하는 것과 같다.

- 가격협상이 가능해요~ (네고가능)
*** Templated Solution
#+begin_quote
I spend one time time now, so that I never have to do it again.

I should not solve the problems twice.
#+end_quote
** What I did WRONG
*** Looking for NEW CUSTOMERS
#+begin_quote
You can sell to one person, ETERNALLY.

They probably still be skinny and swole, or more swole than they are.

기존의 고객들에게 관심을 가지고, 다른 문제점을 고민하고
그 문제를 해결할 방법을 찾아내, 그들의 문제를 해결하고
돈을 번다.
#+end_quote

*** Stopped For New
#+begin_quote
Don't find new things. you have to improve old things again and agian.
#+end_quote

*** No offers & No sales script/process
You have to make sales script _immediately_!

*** Don't Charge More
You have to charge more money, if you don't have much time to deal with.

*** Worried about peer judgement
선택의 기준은 나 스스로가 되어야 한다.
남에게 휘둘리지 않을 사고력을 갖추어야 한다.

*** Didn't Get Help
** Words of advice for anyone starting
*** Follow Instructions
*** When you reach somethign you don't understand how todo -> Google First
*** When you figure it out, post it.
Others may have struggled.

*** Actually follow rule of 100 daily
Business become inconsistent because they are inconsistent

Do more faster more consistently.
*** You will be excited for a week. Then the excitement will wear off
That's when the work begins.
*** You work works on you more than you work on it
You are the product

무의미함과 무가치함은 사람을 고통스럽게 한다

나의 스킬을 증가시키는데 이용되는 모든 일들은 가치가 있다

*** Everything is unscalable in the beginning.
That's the point

모든 작은 부분을 배운다면, 그 분야에서 마스터가 된다.

작은 부분을 많이아는 사람이, 다른 사람에게 "잘하는 사람"으로 느껴진다.

난 더 나은 방법을 찾아야 해.

고통을 다루는 방법을 찾, 더 나아져야해

*** The pain of repetition is what forces you to seek improvement.
*** If you complain, you're dead to me.
불평은, 아무런 결과를 얻지 못하는 곳에 힘쓰는 행동이다.

**** 불평이 보상받는 상황
Affection (애정)
Attention (관심)
Approval (승인)

**** It is better to be envied than pitied
*** Literally thousands of people have succeded.
You are not special

1. 잘하는사람 _그대로_ 따라하기
2. 반응이 좋지 않다면, 그들과 내가 다른점 분석하기

내가 실패했다고 해서, 그 방법이 잘못된게 아니다.
내가 정확한 방법을 모르기 때문이다.

*** Write down every reason you're going to stick with it
무언가 하고자하는 욕구 (동기)는 매우 빨리 사라진다.

내 현재 상황이 마음에 들지 않는다면, 그것을 적고 매번 하기 싫은 일을 할때 마다 보라.

*** Business is shockingly =SIMPLE= but surprisingly =HARD=
Hard part is consistency. Because you have to keep doing it.
*** Just win
Once win, everything else that you did to get to ther will fade.

The pain that you are going through right now will fade,
but the result that you get will stay with you.


* The Rule of 100
100 "REPS" of advertising every day when you're early in business

#+begin_quote
Please, Let people know that you exists!
#+end_quote

** 100 warm out reaches
You need to reach out to people who know you

#+begin_quote
Mine you don't have to be your homies
#+end_quote

*** The Rule of 300
**** Post contents 1 piece
**** Do 100 comments
#+begin_quote
A goal of the comments is to make the best comment
#+end_quote

Do it inside of a group:
- going to be a pool of ideal customers

경쟁을 줄여, 나를 돋보이게 만든다
- 커뮤니티 -> 댓글

처음엔, 내 게시글 보다, 인기 많은 글의 댓글이 접근성이 좋다
- 아무도 내가 존재하는지 모르기 때문에, 알려야한다

**** New warm list
Anyone who liked your post
Anyone who comments your post
Anyone who liked your comment
Anyone who replied your comment

#+begin_quote
Because they take a action
Becuase they indicated a interest
#+end_quote

1-1 Outreach

#+begin_quote
Hey, I saw you liked my content what about it drew you in?
What made you do that?

Quenstion!!
#+end_quote

** 100 cold prospects
You need to reach out to people who don't know you

** spend 100 minutes for making contents & post it

** spend $100 for ads a day
*** spend 100 minutes for making ads
* At the first
1. Making PROOFS
2. Posting PROOFS with some offers and CTA (Call To Action)

** Prioritize Learning Over Earning
To leads the larger rewards in the future,

*** How to invest time in learning skills efficiently?
In our long-term growth.

*** How to gain experience and knowledge effieiently?
**** Meet the mentors.
Who is the mentors?

*** How to compound my advantages?

** Business Ideas
*** Pain - personal struggles
*** Profession - skills from a job
*** Passion - interests

** Customers
To build a strong connection with potential customers

*** How to understand their specific needs and pain points?

** Offers
To create a compelling offer that emphasizes ease, speed, guaranteed resutls, and a pain-relief element for customers,

*** What do I needs?

** Unique Mechanism
You have to stand out among competitors for specific people.

** First 5 clients
My known peoples
