* Today's Issues
Video translate contents

* Mindfulness
Am I truly present and in the moment?
Was I mindful at that moment?

Not really. I just doing while don't thinking well

* Love (benevolence)
Did I put myself in other people's shoes and consider their feelings?

Particularly.

* Justice
Didn't I treat others as I wouldn't like to be treated?

Not completely.

* Harmony (Politeness, Respect)
Did I think, speak and behave appropriately for the situation?

I had to message to him about this topic before upload

If i want to be comfortable, i had to dig in about this subject more precisely

* Wisdom
Did I base my selection and determination on true evidence leaving no uneasy feeling?

No i'm not. I'v worried about if it doesn't right.

* Result of The analysis
(Write down the things that needs for further improvement according to the analysis and your conscience.)

If i confused about anything, I have to dig inside of that topic more precise and detailed

I have to get permission to others, if i want to use their contents.
- because i don't know how they feel. may be they don't like it
- i have to get permission to them, even i think that they like it

* Self Reflection (Insight, Reflection)
I'm quite lazy more than i thought

Hi Thor, i'm one of your fan in Korea.

for last month, i upload your shorts in my TikTok, Youtube and Instagram (translated into Korean)

I'm sorry to don't get your permission eariler..

but i think this is the time.

could i continue uploading your video in my video?

I think Korea needs your mind and atitude

If you don't like, i want to delete them.

this is my accounts.

TikTok
https://www.tiktok.com/@gutmutcode

Youtube
https://www.youtube.com/channel/UC5GdtbEUYFF7Kc8AUQlIl4A

Instagram
https://www.instagram.com/gutmutcode?igsh=MWZ1bWVzM2ZqeHdoaw%3D%3D

Again, i'm sorry about don't get your permission before
your contents is so enjoyable for me, thank you for that :)
