#+title: Firmware

* What is Firmware?
A program that provides
- the low-level control (initialize) to hardware
- hardware abstraction for a device's specific hardware

Such as [[file:./bios.org][BIOS]] in personal computer

The firmware is smart enought to find those files and load on instead of just loading and executing whatever is in the first sector of the disk

* Features
Provide some diagnostic outputs
Provide a way to configure the hardware
locates and load the boot loader which in turn locates and loads the OS

* How to find information about a specific hardware?
** Datasheet (DS)
- Functional =overview=
- Pin assignment and definition
- Electrical characteristics
- Packaging
- Ordering information

** Reference Manual (RM)
This targets =application= developers.

- how to use the hardware (MCU, memory and peripherals)

** Programming Manual (PM)
This targets application and =system-level software= developers.

- Programming model
- instruction set
- =core= peripherals
* in Arduino Mega
** ATmega8U2 firmwares (하나의 파일)
ATmega8U2를 통해, ATmega2560에 Serial 접근할 수 있도록 만듬 (Port 생성)

 - ATmega8U2 DFU bootloader
 - usb to serial firmware
