#+title: 단

* 단 (丹)
우물안의 붉은 빛의 수은 광 물질

옛 중국에서 경련이나 발작을 진정시키기 위해 사용했다

* 눈에 끌리는 내용
** 지혜와 용맹
삼국지에서는 장비가 아니라 관우라도 공명앞에서는 아무것도 아니었지만, 거기서는 달랐다.
전쟁을 승리로 이끈 사람은 언제나 공명이 아니라 장비였다.
지혜보다는 용맹이 모든것을 해결해 주었고, 그 용맹을 담당한 것이 다름 아닌 박정표 바로 그 녀셕이었던 것이다.

** None Kind
*** 1
도사든 도인이든 이름이야 아무러면 어떤가? 어때? 만나 보려나?

*** 2
아, 아, 관두게, 관둬! 공자 앞에서 문자 쓰긴가?

엉터리 공자니까 하는 말이 아닌가? 그처럼 동양사상에 해박한 척 해놓고서 도인? 도사? 뭐 이렇게 유치원생 같은 반문을 하고 있으니 자넨 헛걸세, 헛거!

*** 3
원래부터가 행동적인 정표였었다. 내가 사색이니, 명상이니 하며 이론 비슷한 걸 취미삼은 데 비해서 정표는 일단 움직이고 보는 성미였었다.
그런 정표였는지라 그는 나를 가리켜 늘 실속없는 아웃사이더라고 놀려대었었다.
정표의 주장인즉 모든 것은 직접 뛰어 들어서 겪어 보아야 한다는 거였다.
늘 빙글빙글 주위로 돌면서 관찰하고 분석하고 검증해 보아야 무슨 소용이 있느냐?
이론이라는 건 행동하자고 있는 건데, 평생 이론에만 매달려서 아무것도 성취하지 못할 바에야 실패하더라도 일단 뛰어 들어야 한다는 게 그 친구의 일관된 주장이었었다.

물론 난 늘 맞섰다. 뛰어들라 하지만 그곳이 어떤 곳인 줄 모르잖느냐?
혹 잘못된 곳에 빠져버릴 염려가 있다.
그러니 우선 뛰어 들어야 할 곳을 판단해야 한다.
이론은 그래서 필요한 것이다, 라고

그렇지만 정표는 내 말에는 귀를 기울이지 않았었다.

**** 마음이 쏠리는 일이라면 무엇이든 저질러 놓고 보는 성미였던 것이다.
한때는 세상에서 사교라고 지탄받는 종교에도 가담했었고, 그런가 하면 건실하다는 기독교에 귀의한 일도 있었다.
그 뿐만이 아니었다.
나와 소식이 두절된 뒤로는 무슨 심령과학인가 하는 데 매력을 느껴서 3~4년 정도 몰두하기도 했던가 보았다.
(Mind control - Jose Silva)
그러다가 과학적 근거와 충분한 자료의 뒷받침을 받는 미국의 새로운 정신계발법ㅂㅂ에 마지막으로 귀착하였다고 한다.
무려 10년에 가까운 정신편력의 종착점이었던 것이다.
그러나 그것도 4~5년만에 이번에는 자기 나름의 새로운 이론과 행동법을 들고 나오게 된 것이다.
흔히 마인드 컨트롤이라고 불리는 데에다가 자기가 나름대로 겪고 느낀 것들을 조합하여 새로운 정신계발법을 개발했다는 것이었다.

역시 정표란 녀석은 나처럼 방관자는 아니었던 것이다.
정표는 직접 염력을 실험하였고, 또 성공했노라고 내게 말하였다.
지금 당장이라도 내 앞에 쇠로 된 스푼을 휘어 보이겠노라고 장담했던 것이다.

염력현상이 어떠한 특수한 체질의 사람에게만 가능했을 때 까지는 이원론도 할 말이 있었을지 모른다.
그러나 이제 평범한 여늬 사람에게도 염력이 있다는 것이 증명되어 간다는 것이었다.

한때 몇몇 가지 종교에 거의 미치다시피 열성을 보인 바 있는 정표는 기도의 놀랄 만한 치유효과를 여러 차례 목격했다고 한다.

대야에 물을 떠나가 방안에 놓는다. 물론 방문을 닫아서 외풍을 없게 해야 한다.
물이 고요해지기를 기다려 수면에 나뭇잎 한장을 띄워 놓는다.
나뭇잎은 대야 한가운데 미동도 않고 떠 있다.
여기에 바람이 불지 않으므로 당연히 그것은 움직이지 않는다.
이렇게 해 두고서 거리를 두고 자리에 앉았다.
이제 부터 집심이 시작된다.
남아있는 것이라고는 나뭇잎이 움직이기를 원하는 간절한 마음 그것뿐이었다.
처음엔 꽤 시간이 걸렸다고 한다.
마침내 나뭇잎은 가볍게 일렁인다.
그리고는 서서히 물살을 헤치면서 정확하게 대야의 오른편 끝에 가서 닿았다.
이것만으로는 아직 충분하지가 않다.
이 염력술사의 염은 계속되었다.
한참이 지나자 나뭇잎은 180도로 완전하게 회전하였고, 다시금 천천히 중앙을 향해 전진해 나아갔다.
드디어 해낸 것이다.
정신이 물질계를 직접 움직일 수 있다는 것을 드디어 증명해 보여 준 것이다.
되풀이 연습을 한 결과 처음보다 시간도 단축이 되었고, 그다지 힘들지도 않게 되었다.

염 - 아직 오지 않은 것
상 - 이미 있었던 생각

수면 위에서 나뭇잎을 자유자재로 움직일 수 있게 되자, 정표는 강렬한 희망과 왕성한 의욕을 가지고 마침내 대망의 스푼밴딩의 실험에 돌입하였다.

*** 4
그까짓 숟가락 한 자루 구부린 게 뭐 그리 대수로운 일인가?
그래서 얻은 게 뭐야? 국가재산만 축내지 않았나?

정표는 어느 누구에게도 자기가 스푼밴딩을 실험하고 있노라고 얘기한 일이 없었다.

*** 5
아침식사가 끝나자 스푼밴딩의 복습에 들어갔다.
그런데 이게 웬일인가?
되질 않는다.
두 시간 가까이 용을 써 보았지만 ㄱ자는 고사하고 꼼짝도 하질 않는다.
스푼을 만져 보았지만 휘려는 조짐도 없다.

"그 결승인지 준결승인지 하는 자 때문이야!"

그러나 생각해 보면 그 사람 때문일 리가 없다.
그 사람 때문에 잡념이 들어와서 집심이 안되었다 하더라도, 그 잡념이 들어오게끔 허용한 것은 결국 나 자신인 것이다.
그 위라는 사람에게도 일말의 혐의가 없는 것은 아니지만, 궁극적인 책임은 나에게 묻지 않으면 안된다.

이렇게 생각하고서 뒤로 후퇴를 해서 대야 위에 나뭇잎을 띄우던 전단계로 되돌아 갔다.
그런데 이것도 역시 되질 않는다.
나뭇잎은 제자리에서 미동도 하지 않는다.

마가 씌운 것일까?
아니면 나뭇잎 운동이나 스푼밴딩은 꿈속에서 있었던 일인가?

어쨌든 속이 부글부글 끓었다.
(저녁 공양시간 주변사람들에게) 뭐라고 욕이나 퍼부어 줄까보다 싶은데 꼬투리가 없다.
화는 나한상 앞에서 폭발이 되었다.
알 수 없는 부아가 발끝에서부터 무지개처럼 솟구쳐 올랐다.

"에잇!"

돌아보니 그 큰 나한상이 스르르 주저앉는다.
쾌감을 느끼기는커녕 은근짜하게 뒤가 켕기는 게 사실이었던 것이다.
혹 아는가? 저 나한상에 진짜 나한은 아니더라도 무슨 신의 끄트머리 하나쯤 지펴 있을지.
어쨌든 썩 유쾌하지 못한 일인 것만은 사실이었다.

승려들과, 같이 지내는 젊은이들이 서로 마주보며 눈짓을 주고 받았다.
<어서 가십시오 환송합니다>까지는 아니더라도, <그래만 주었으면 좀 좋겠소>하는 눈빛이 완연하다.

"망할 것들! 내가 스푼밴딩이 아니라 금동밴딩까지 해서 이 절의 불상을 확 구부려 놓아 버릴라!

아까부터 이상하게 알 수 없는 울화가 북받쳐 오르는 것이다.

*** 6
"기특한 젊은이라고 격려를 해주려던 것이었는데 그게 그렇게 되었구먼. 미안하이."
- 기특한 행동은 격려해주어야 하는가?

"그땐 죄송했읍니다."
"마인드 컨트롤이라는 게 진짜 마인드를 컨트롤 할 수 있었으면 좋으련만... 역시 <정신>은 근본이 아닌가 봅니다..."

"핫핫핫!"
"그래! 마인드를 컨트롤하려고 의지를 세우는 또 하나의 마인드가 있단 말이지? 그걸 정신의 정신, 마음의 마음이라고 불러도 될까? 옳거니! 바로 그걸세!"

"죄송하지만..."
"어떻게 된 건지 전말을 좀 일러 주시지 않겠읍니까?"

"가세! 자네가 맘에 들었네. 좀 기패가 세긴 하지만 그게 있어야 수련도 할 수가 있겠지."
위결승이라는 사람은 정표의 의견도 묻지 않고서 앞장서서 계곡을 훑어 올라가기 시작했다.

- 기패가 있어야, 수련도 할 수가 있을까?
- 의견을 묻지 않아도 괜찮은가?
*** 7
그러나 전혀 무장도 안된 상태에서 맹수와 마주친다는 건 어쨌거나 소름이 쫙 끼치는 일이 아닐 수가 없었다.
다만 웬지 모르게 이 위결승이라는 사내의 침착함과 의연함이 마음에 위로가 되었다.
- 침착함과 의연함의 근원은 무엇일까?

이 사내가 자기 말처럼 여기서 열 일곱 달 동안이나 홀로 살아 왔다면, 내가 왜 하룻밤쯤 예서 묵지 못하랴 하는 오기도 생기는 것이었다.
- 의도한 것일까?

*** 8
자네는 왜 그런 외래식 공부에만 열중하는 겐가?

기독교라는 건 분명 우리 종교가 아니었다.
마인드 컨트롤도 미국서 시작된 것이며, 심령과학을 비롯해서 정표 자신이 알고 있는 철학,종교,과학이론의 거의 전부가 외래식이라면 외래식인 것은 사실이었다.
하지만 어쩐단 말인가?

"세계는 넓습니다. 왜 하필 우리 것이어야 합니까? 선진국으로부터 배울 것은 배워야지요!"

"선진국?"
- 선진이란 무엇인가?

"그렇죠. 보십시오. 지금 세계를 지배하는 게 누굽니까?"
- 세계를 지배하는게 선진인가?

"여보게..."
위결승 씨는 기가 막히다는 듯이 말했다.
"여보게, 지금이 몇 년인지 아는가?"
- 왜 물어보셨을까?

"몇 년이라뇨? 도대체 무얼 물으시는지 알 수가 없읍니다."

"올해가 도대체 단기 몇 년이던가?"

"아, 네... 2333이니까 1983에다 2333을 더하면..."

"이사람! 박.정.표.군!"

벽력 같은 호통과 함꼐 자기의 이름이 토막토막이 되어 귓전을 때려왔다.
위결승 씨는 단단히 화가 난 모양이었다.
무서운 안광으로 정표를 쏘아보면서, 그러나 태도만은 여전히 침착했고 예의 튼튼한 가부좌만은 그대로 유지하고 있었다.
- 왜 화가나셨을까?

"죄송합니다. 세상이 세상이니만치..."

"내게 사과할 건 없네. 하지만 바로잡을 것은 바로잡아야겠어. 차라리 일제치하에서 우린 더 민족적이었을 거야. 해방 이후 우리들이 해온 꼬락서니라니, 그건 추종도 아니고 모방도 아냐! 그건 어중이떠중이일 뿐야. 그리고 그건 지리멸렬이고 횡설수설이고 한 마디로 엉망진창이 아닌가?"
"그들이 과학의 선진국인 건 나도 아네. 하지만 그들이 정신면에서도 선진국이란 말인가? 미국이란 나라 숱한 사회문제로 골치를 썩히고 있는 거 자네도 알지? 그래서 탈출구를 찾지 못한 젊은이들이 반전데모다 히피다 마약이다 해서 거리로 쏟아져 나왔었는데, 요샌 동양사상이 인기라면서? 크리슈나무르니티 라즈니쉬니 하는 이들의 책이 베스트셀러가 되는가 하면, 선도하고, 요가도 하고, TM도하고, 주역-우파니샤드에도 관심들이 많다고 들었네. 그들은 그 잘난 선진과학으로 아담이 잃어버린 낙원을 되찾는 데 실패한 거야!"
"지혜는 바로 우리에게도 있는 걸세. 왜 찾지 않는가? 왜 우리 것을 찾지 않느냔 말일세. 그 잘난 서구식 방법으로 자넨 숟가락을 휘는데 무려 일곱 달이 걸린 모양이네만, 어떤가? 자네는 내 마음을 들여다 볼 수가 있겠나? 여기 앉아서 집 밖에서 일어나는 일을 투시할 수가 있겠나?"

"그렇다면..."
"그렇다면 그건 투시였읍니까?"

"허어..."
위결승 씨는 기가 막히다는 듯이 혀를 끌끌 찼던 것이다.
*** 9
신선놀음에 도끼자루 썩는 줄 모른다는 속담 정도에다가, 신선하면 도복을 입고 꼬불꼬불 이상한 지팡이를 짚은 모습에 더러는 학을 타고 날아간다는 정도가 보통, 사람들에게 알려진 선도였다.
그런 것이라면 전설이나 재담 이상의 아무런 의미도 없는 것이다.
도대체 어디서부터 그 전체면모를 포착할 수 있을 것인가?

선도의 목적은 무엇일까? 신선이 되는 것? 그렇다면 그 방법은?
단약을 구해야 한다는 설도 있고, 수련을 해야 한다는 설도 있는 모양인데,
단약이라면 어디서 어떻게 구할 것이며,
수련이라면 누구의 지도를 받을 것인가?
그리고 그런 훌륭한 도가 실제로 존재했었다고 한다면 어찌하여 근거가 남지 않았을까?
신선이 되어 날아갔다고 전하는 장량도 다른 기록에 의하면 졸했다고 적혀 있고,
불로초를 구하러 봉래산으로 떠났다는 서시 일행도 결국은 실패하였다고 하니, 진시황도 못해낸 그 지난한 사업을 오늘날 누가 해낸단 말인가.

"그게 아닐세"
하고 위결승 씨는 말했다.

"신선이 되자는 얘기가 아냐. 그 방법이 가지는 장점을 살려서 정신계발을 하자는 걸세. 선도에는 현대과학이 따르지 못할 만큼 탁월한 효과가 있는 숱한 비법이 있거든. 우선 간단한 예로 나는 격벽투시를 할 수가 있어. 그뿐인가? 수련이 조금만 정진되면 미래와 과거사를 보게 되네. 한눈에 책 열 페이지나 스무 페이지를 외는 것은 쉬운 일일세. 그런데 이건 암기와는 달라. 암기는 반복에 의해서 습관적으로 남는 현상이지만, 이것은 예컨대 마이크로필름과 같아서 언제든지 재생해 볼 수가 있단 말일세. 십년 후라 하더라도 정확하게 그것을 기억해 낼 수가 있거든. 그밖에도 열거하기 어려울 만큼 많은 능력이 계발된단 말일세. 물론 그것은 우리 내부에 잠자고 있는 능력을 일깨우는 것일 뿐, 이건 결코 사술도 아니고 신비주의도 아냐. 이걸 배워서 신선이 되고 싶은 사람은 되라지. 그러나 내 말은 이것을 활용해서 우리 모두 좋은 세계를 만들어 나가자는 말일세..."

"그렇다면 말입니다."
하고 정표는 묻지 않을 수가 없었다.

"어째서 그 놀라운 정신계발법이 아직껏 인류역사의 표면에 나타나지 않았읍니까? 배운이들이 모두 우화등선해 버렸던가요?"

"자네가 모르는 말일세. 자네 혹시 김시습이 단학을 수련했다는 걸 알고 있나?"

"전혀 처음 듣는 얘깁니다"

"그것 보게. 김시습은 단학 즉 신선도 수련에 관한 저서까지 낸 사람일세. 아다시피 그는 천재일세."

"사실인가요? 그 책의 이름이 뭡니까?"

"천형, 용호, 복기, 수진일세. 그럼 자네 혹시 홍의장군 곽재우가 선도수련가였음은 아는가?"

"임란의 명장 곽재우 말입니까?"

"물론! 같은 이름의 다른 장군이라도 있었던가? 보게. 장군께서 지으신 한시가 여기 있네."
(이능화 - 조선도교사, 선도와 도교에 관해서 여러 자료를 집술한 것)

"홍만종의 해동이적과 명신록, 이수관의 지봉유설등에 곽 장군의 기사가 보이네."
"우리는 신라시대에 화랑도가 유불과 나란히 한 류의 가르침으로 생생하게 살아 있었음을 알고 있네. 이거야말로 국선도일세."

"그렇다면 왜 일반에게는 잘 알려지지 않았을까요?"

"우선 하나는 이기심일 거야. 또는 달관의 결과라고나 할까. 그건 이렇네. 선도의 고수? 좀 뭐하네만 아뭏든 높은 경지에 오르게 되면 세상일의 앞뒤가 명경알 같이 훤히 내다 보이게 된단 말일세. 그러니 어떻게 되겠는가? 이미 운수가 정해진 일에 뛰어들어서 되지 않을 헛된 노력을 할 필요가 있을까? 내가 아니어도 될 일은 되고, 내가 나선다 해도 안될 일은 안될 거라고 한다면 구태여 세파에 몸을 더럽히고 싶지 않았을 테지. 게다가 당시의 사회풍토 속에서 자칫 잘못하다가는 이단이네, 사문난적이네, 요망한 무리네 해서 살아 배기기도 어려웠을 테고, 고려시대엔 불교가 국교로 인정되었고, 근세조선시대엔 유교가 좀 극성스러웠는가? 그뿐인가? 선도란 지난한 것인데 섣부르게 선기를 누설했다가 제자가 다 배워내지 못하게 되면 무슨 누가 될 것인가? 이런 저런 이유 때문에 모두들 굳게 입을 다물거나, 혹 저서를 남긴다 해도 옥추경에서 보듯이 난해한 괘효를 사용했기 때문에 후인들로 하여금 진위를 분간하기 어렵게 하거나, 교묘한 방법으로 묵시적 표현을 사용했을 것이네."

"나머지 한 가지 이유는 뭡니까?"

"비단 선술이 아니더라도 모든 이기란 결국 흉기이기도 하거든. 비인부전 일세. 그러나 누가 참된 그릇이란 말인가? 대개의 종교는 대부분 교종과 심종으로 되어 있는 법인데 선도란 예컨대 심종이야. 정밀하게 사람을 분별하여 남모르게 의발이 전수되니 일반인들이 알 수 없는 건 당연한 게지."

"그렇군요"

"선도를 통한 공부란 정북창에 의하면 역리 공부일세. 북창 정렴은 말했지. 그는 선학파에서는 널리 알려진 분일세. 북창에 의하면 공부에는 순리공부(세속적 학문?)와 역리공부가 있네."

"삼가 생각컨데 고인이 말하기를 순리로 하면 사람이 되고, 역리로 하면 신선이 된다고 한다. 대개 하나가 둘을 낳고, 둘은 넷을 낳고, 넷은 여덟을 낳고 하여 64에 이르고, 더 나아가 만사에까지 이르는 것이 인도이다. 가부좌를 틀고 단정히 앉아 발을 드리운 듯이 눈을 감고 만사의 분요한 잡념을 걷어치우고 일심을 아무것도 없는 태극에 돌리면 태극이란 곳이 곧 선도인 것이다."
"이처럼 공부에는 두 가지의 길이 있는것일세. 공문의 예를 들어 볼까? 역경 계사전에 이런 귀절이 있네"

/역은 무사야하며 무위야하야 적연부동이라가 감이수통천하지고하나니, 비천하지지신이면 기숙능여어차재리오./

"그건 이런 뜻일세. <역이란 생각함도 없고 행위하는 것도 없이 고요히 움직이지 않으면서도 결국 천하의 연고를 느껴 통하게 되는 것, 하늘 아래 지극히 신력한 자 아니면 그 누가 이러할 수 있으랴.>"
"계사전은 공자께서 역경 원문을 증연하신 것으로 알려져있네. 그렇다면 이 귀절 또한 공자의 말씀인 거야. 그런데 어떻게 <고요히 앉아서 천하만물의 변화를 다 알 수>가 있단 말인가? 이야말로 유교의 심법인 것일세."
"우리는 흔히 유교에는 심법이 없고 다만 일용사물지학일 뿐으로 알고 있는데 오핼세. 우리에게 익히 알려진 논어, 중용, 대학등의 책은 확실히 정치학, 윤리학적 요소가 많은 게 사실이네. 물론 약간의 형이상학이 없는 건 아니지만. 그런데 이걸 후대에 전한 주체가 누구던가? 증자가 아닌가? 증자는 공문의 교종일세. 불교의 아난이나 사리불에 해당된다고나 할까? 공문의 심종은 안자야. 불교의 마하가섭이지. 그런데 불행하게도 안자가 서른 세 살로 일찌기 돌아가심으로 해서, 심종은 다시 공자의 묵시로 거슬러 올라가 근거를 구하지 않으면 안되게 되었네. 그러니까 유교에서 심종이 약화된 비극은 전적으로 안자의 조졸에 있었던 거야. 그런데 이 유교의 심법 또한 선도와 다르지 않네. 이 점이 중요해. 장량, 진평 등이 장막 안에 앉아서 천리밖의 일을 손바닥 보듯 알았다는 건, 그들이 정신수련에 정통했음을 단적으로 증명하는 것일세. 유명한 예로 제갈공명은 왜 언제나 백우선을 들고 다녔는지 자넨 아는가? 부채가 겨울철에 무슨 소용인가? 그런데도 그는 일년 내내 부채를 가지고 다녔네. 그것은 그의 도사 복색과 무관한 게 아닐세."

"그럼 제갈공명도?"

"허어... 안되겠구먼. 내가 우학도인을 뵙도록 해 줌세. 우학도인이야말로 우리나라 단학선도의 도맥을 쥐신 분일세. 그분에게서 자네는 많은 시사를 받을 수 있을 거야. 내 짧은 지식도 그분으로부터 배운게 대부분일세. 자, 오늘은 이만 자고 내일 일어나서 이야기도 더 하고, 집구경도 하고 하세나그려."

"선생님 이야기도 듣고 싶습니다."

"싫어! 내 전력은 공개하지 않기로 하고 있네. 자네가 우학 선생님 이야기를 듣고 나면 내 이야긴 상대적으로 왜소해 보일 테니까. 핫핫핫! 허나 꼭 그 때문만은 아닐세. 자, 이만 잘까?"

*** 10
"모두가 그런 식이었네."

"그동안 난 여기서 지난날의 방황과 무절제를 참회하고 있었지."
- 방황의 참회는 필수적인가?

"그리고 겸해서 우학선생님을 뵐 사전 준비도 해두었지. 손이 닿는대로 동양사상 전반과, 과학, 철학 또는 선도에 관한 책들도 읽고... 어때? 다음 주쯤 나랑 동행하지 않겠나?"

"자네까지 신기한 사람으로 보이는 마당일세. 생각해 보지."

"고맙네. 허락해 주어서. 다음 주 토요일일세. 종로에 있는 호수 다방에서 만나세. 여섯시까지 오면 좋을 거야"

"이 친구! 난 허락하지 않았어!"

"한 번 뵙고 맘에 들지 않으면 빠지게나. 그렇지만 그렇게는 안될걸! 자네는 결코 이 기막힌 세계로부터 빠져 나갈 수가 없을걸세. 자, 이제 그간 밀렸던 친구로서의 이야기나 할까?"

* 박정표 군의 추천
** 촛불끄기
*** 촛불을 켜서 눈보다 10~15도 상방에 위치시킨 다음 앉는다.
*** 그리고나서 먼저 호흡을 고른 후 양껏 크게 숨을 들이쉬고 멈춘다.
*** 그후 눈으로 촛불을 직시하면서(눈물이 날 것이나 참는다) 두 팔을 뻗어 손끝으로 촛불 전방 5cm에서 (초보자라면) 촛불을 겨냥하고 기가 나가 불이 꺼진다고 강력하게 생각한다.
*** 한 번에 되지 않으면 반복한다.
*** 10~30 분 정도에, 웬만한 집중력을 가진 사람이라면 촛불이 출렁이거나 꺼지는 것을 보게 될 것이다.
*** 익숙해지면 1~2m 전방에서도 가능하게 된다.
*** 즉, 장풍인 것이다.

* 박정표 군의 실험성적
** 정신치료
** 정신력으로 알콜도수를 변화시키기
** 식물성장촉진염력
* 단학
우리 민족 고유의 선도이다. (신선을 배우는 도)
세상에는 단약을 만들어서 먹음으로써 신선이 되는 것으로 알려져 있고, 또 책에도 그렇게 기록된 데가 많다.
만령단이니 은단이니 하는 약제들도 둥글게 뭉친 것이라 뜻 외에 이런 신선도의 영향이 있었을 것이다.
그러나 우학도인에 의하면 단이란 자기의 내부에서 형성되는 원신, 즉 요즈음 말로 하면 <진정한 자기>이다.
그것은 수련을 통해서 처음에는 기로써 단전에 모인다고 한다.
단학이란 말은 단전이란 말과도 관계가 있다.

** 조식
호흡을 고르게 하는 것으로부터 수련이 시작된다. 호흡은 선도 수련의 시작이며 끝이다.

** 벽곡
음식을 먹지 않는 것. 또는 아주 극소량만 먹는 것.
여러가지 정신, 육체적인 이로움이 있다.
