#+title: mind

* Mind always like chaos
** Protect mind from invasion of disturbance

bad things can't invade our mind when our mind is filled with others

어떠한 잡념의 방해도 받지않고, 원하는 생각만을, 일정 시간만큼, 기분 좋게 유지할 수 있다면, 인생은 지금 이 순간부터 달라질 것

*** Recite
*** Inhale
*** Exhale
*** Don't know
*** Alright - It's OK

* Breath is life
because stopping breathing means death

** Mind and Breath are connected
It's easier to control breathing than to control your mind

/Always observe your breath/

breathing control is the same as mind control

breathing supply oxygen to the body, and get the carbon dioxide out from it
oxygen helps our body grow, reproduce, and turn food into energy

* Block the bad thoughts
** why bad thoughts lead you to failure
If you have bad thoughts, your view point is narrowed, so you cannot make the right decision

and that narrowed view point affects your creativity, making it harder to find solutions to your problem

so there's no success and happiness without diconnection with them

the way is very simple.

say "I don't know" to them.

if dosn't go away, then say that again

repeat it until bad thoughts go away

the best way to this is saying "I don't know my name"

Bad thoughts can't stick if you don't know the name

You are failed if you concentrate on bad thoughts and give them energy

The best way to avoid the fraud is refuse conversation

You just need ignore them

#+begin_quote
"조건을 따지지 않고 곧장 만족해버릴 수 있다면 늘 만족할 수 있을 것이다." - 노자
"You can always be satisfied, if you can be satisfied without any conditions" - Laozi (Chinese Philosopher)

"늘 기뻐하십시오. 끊임없이 기도하십시오. 모든 주어진 것에 감사하십시오!" - 사도바울 (데살로니가 전서5:16 ~ 18)
"Rejoice always. pray continually, give thanks in all circumstances!" - Apostle Paul (1 Thessalonian 5:16 ~ 18)
#+end_quote

recite and recite again

breathing is controlled by the conscious and unconscious mind


* What we are
** me 10 years ago and right now

#+begin_quote
몰입이란 정신을 하나로 통일하는 것 일 뿐이다.

일이 없을때는 마음을 맑고 편안하며 고요하게 하되 요동치지 않게 유지하는 것이며

일이 있을때는 일에 따라 대응하고 변화하되 마음이 다른 데로 가지 않게 하는 것이다.

이것이 "지금 하는 일에 집중하는 것이 바로 깨어있음이다" 라는 것이다.

- 퇴계 이황 -
#+end_quote

* Happiness
** 행복의 조건

*** 남과의 비교에서, 상대적으로 우월감을 느낄때

행복하려면, 항상 남보다 잘나야만 한다

나보다 잘난 사람은 어디에나 있다
-> 모든 분야에서 남들보다 뛰어난 능력을 갖추는 것은, 불가능하다
-> 결국 행복할 수가 없다.

자신이 상대적으로 우월할때 행복,
자신이 상대적으로 저능할때 불행,
자신의 우월은 드러냄,
자신의 저능은 감춤,
외부에서 서로의 우월한 부분을 보기가 쉬움,
외부에서 서로의 저능한 부분을 보기가 어려움,
상대적인 저능하다고 느끼기 쉬워짐
-> 비교에의해, 대부분의 경우에 불행을 겪음
-> 자신의 저능을 감춰야하기에, 사회에 자신을 드러내지 않음

*** 원하는 것을 이루었을때

목표를 이루었을 때만 행복하다
-> ~이루는 과정~ 내내 불행하고, 불안하다 -> 어떻게 하면, 이루는 과정내내 행복할 수 있을까? -> 몰입, 지금 당장 행복하기
-> 막상 이루었을때, 내가 원했던 행복감이 오는 것도 아니다

목표를 이루었을때 얻을 수 있을 것이다고 예상했던 행복감은,
우리가 멋대로 상상했던 "판타지"에 불과한 것

실제로 이루어진 욕구가, 우리를 허무하게 만든 경우를 경험해보지 않았나?

큰 기대를 안고 이룬 목표
-> 우리에게 예상했던 행복감을 보상해주지 않는다.
-> 오히려 허탈감을 남기는 경우가 많다.


* Joy of learning
* 욕심
고통을 감수할 마음이 있다

* 맡겨버리기
맑음을 추구하지만 말고

탁기도 내거다

남의 탁기에 휘청인다면?

사회생활

중생구재를 못한다

* 업
생각 감정 오감 행위 -> 과보
